/**
 * Output formatter — converts analysis results into readable markdown.
 */

import type { ConsensusResult, PerspectiveResult } from "./analysis/types.js";

const VERDICT_EMOJI: Record<string, string> = {
  approve: "[APPROVE]",
  reject: "[REJECT]",
  caution: "[CAUTION]",
  abstain: "[ABSTAIN]",
};

const AGREEMENT_INDICATOR: Record<string, string> = {
  unanimous: "Unanimous",
  strong: "Strong Agreement",
  split: "Split Decision",
  contested: "Contested",
};

export function formatConsensusResult(
  consensus: ConsensusResult,
  proposalId: string,
  realmPath: string
): string {
  const lines: string[] = [];

  lines.push(`# DAO Governance Analysis — Proposal #${proposalId}`);
  lines.push(`**DAO:** \`${realmPath}\``);
  lines.push("");

  // Overall verdict
  lines.push(`## Verdict: ${VERDICT_EMOJI[consensus.overallVerdict]} ${consensus.overallVerdict.toUpperCase()}`);
  lines.push(`- **Confidence:** ${Math.round(consensus.confidence * 100)}%`);
  lines.push(`- **Agreement:** ${AGREEMENT_INDICATOR[consensus.agreementLevel]}`);
  lines.push(`- **Perspectives analyzed:** ${consensus.perspectives.length}/3`);
  lines.push("");

  // Summary
  lines.push(`## Summary`);
  lines.push(consensus.summary);
  lines.push("");

  // Per-perspective breakdown
  lines.push(`## Perspective Breakdown`);
  for (const p of consensus.perspectives) {
    lines.push("");
    lines.push(`### ${capitalize(p.perspective)} ${VERDICT_EMOJI[p.verdict]}`);
    lines.push(`**Model:** ${p.model} | **Confidence:** ${Math.round(p.confidence * 100)}%`);
    lines.push("");
    lines.push(p.reasoning);

    if (p.risks.length > 0) {
      lines.push("");
      lines.push("**Risks:**");
      for (const risk of p.risks) {
        lines.push(`- ${risk}`);
      }
    }

    if (p.recommendations.length > 0) {
      lines.push("");
      lines.push("**Recommendations:**");
      for (const rec of p.recommendations) {
        lines.push(`- ${rec}`);
      }
    }
  }

  // Consolidated risks & recommendations
  if (consensus.keyRisks.length > 0) {
    lines.push("");
    lines.push(`## Key Risks`);
    for (const risk of consensus.keyRisks) {
      lines.push(`- ${risk}`);
    }
  }

  if (consensus.keyRecommendations.length > 0) {
    lines.push("");
    lines.push(`## Key Recommendations`);
    for (const rec of consensus.keyRecommendations) {
      lines.push(`- ${rec}`);
    }
  }

  // Disclaimer
  lines.push("");
  lines.push("---");
  lines.push(
    "*This analysis was generated by AI models and should not be considered expert advice. " +
    "Always review proposals independently before voting. " +
    "Raw on-chain data was used as input — verify claims against the chain directly.*"
  );

  return lines.join("\n");
}

export function formatHealthResult(
  result: {
    healthScore: number;
    strengths: string[];
    weaknesses: string[];
    recommendations: string[];
    summary: string;
  },
  realmPath: string,
  model: string
): string {
  const lines: string[] = [];

  lines.push(`# Governance Health Report`);
  lines.push(`**DAO:** \`${realmPath}\` | **Model:** ${model}`);
  lines.push("");
  lines.push(`## Health Score: ${result.healthScore}/100`);
  lines.push("");
  lines.push(result.summary);

  if (result.strengths.length > 0) {
    lines.push("");
    lines.push("## Strengths");
    for (const s of result.strengths) lines.push(`- ${s}`);
  }

  if (result.weaknesses.length > 0) {
    lines.push("");
    lines.push("## Weaknesses");
    for (const w of result.weaknesses) lines.push(`- ${w}`);
  }

  if (result.recommendations.length > 0) {
    lines.push("");
    lines.push("## Recommendations");
    for (const r of result.recommendations) lines.push(`- ${r}`);
  }

  lines.push("");
  lines.push("---");
  lines.push("*AI-generated analysis. Verify against on-chain data.*");

  return lines.join("\n");
}

export function formatTreasuryAudit(
  result: {
    healthRating: string;
    findings: string[];
    risks: string[];
    recommendations: string[];
    summary: string;
  },
  realmPath: string,
  model: string
): string {
  const lines: string[] = [];

  lines.push(`# Treasury Audit`);
  lines.push(`**DAO:** \`${realmPath}\` | **Model:** ${model}`);
  lines.push("");
  lines.push(`## Rating: ${result.healthRating.toUpperCase()}`);
  lines.push("");
  lines.push(result.summary);

  if (result.findings.length > 0) {
    lines.push("");
    lines.push("## Findings");
    for (const f of result.findings) lines.push(`- ${f}`);
  }

  if (result.risks.length > 0) {
    lines.push("");
    lines.push("## Risks");
    for (const r of result.risks) lines.push(`- ${r}`);
  }

  if (result.recommendations.length > 0) {
    lines.push("");
    lines.push("## Recommendations");
    for (const r of result.recommendations) lines.push(`- ${r}`);
  }

  lines.push("");
  lines.push("---");
  lines.push("*AI-generated audit. Verify against on-chain data.*");

  return lines.join("\n");
}

export function formatRiskAssessment(
  result: {
    riskLevel: string;
    risks: Array<{
      category: string;
      description: string;
      severity: string;
      mitigation: string;
    }>;
    overallAssessment: string;
  },
  proposalId: string,
  realmPath: string,
  model: string
): string {
  const lines: string[] = [];

  lines.push(`# Risk Assessment — Proposal #${proposalId}`);
  lines.push(`**DAO:** \`${realmPath}\` | **Model:** ${model}`);
  lines.push("");
  lines.push(`## Overall Risk: ${result.riskLevel.toUpperCase()}`);
  lines.push("");
  lines.push(result.overallAssessment);

  if (result.risks.length > 0) {
    lines.push("");
    lines.push("## Identified Risks");
    lines.push("");
    lines.push("| Category | Severity | Description | Mitigation |");
    lines.push("|----------|----------|-------------|------------|");
    for (const r of result.risks) {
      lines.push(
        `| ${r.category} | ${r.severity} | ${r.description} | ${r.mitigation} |`
      );
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("*AI-generated risk assessment. Verify against on-chain data.*");

  return lines.join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
