import { act, fireEvent, render, screen } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { CommunityNews, CommunityNewsPrompt } from "./CommunityNews"
import { COMMUNITY_NEWS_KEY } from "./newsState"
import { useSigner } from "../sign/signerContext"
import { beginWalletActivity } from "../../lib/walletActivity"

vi.mock("../sign/signerContext", () => ({ useSigner: vi.fn() }))
const advance = (ms: number) => act(() => { vi.advanceTimersByTime(ms) })
const prompt = () => screen.queryByRole("complementary", { name: "News announcement" })
beforeEach(() => {
    localStorage.clear()
    vi.useFakeTimers()
    vi.spyOn(document, "hidden", "get").mockReturnValue(false)
    vi.mocked(useSigner).mockReturnValue({ pending: [] } as never)
})
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks(); vi.unstubAllGlobals() })

describe("community announcement", () => {
    it("waits twenty seconds without taking focus, and never repeats after presentation or dismissal", () => {
        const first = render(<><button>Working</button><CommunityNewsPrompt enabled openNews={vi.fn()} /></>)
        screen.getByRole("button", { name: "Working" }).focus()
        advance(19_999)
        expect(prompt()).toBeNull()
        advance(1)
        expect(prompt()).toBeVisible()
        expect(screen.getByRole("button", { name: "Working" })).toHaveFocus()
        expect(localStorage.getItem(COMMUNITY_NEWS_KEY)).toBe("shown")
        first.unmount()
        const second = render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(60_000)
        expect(prompt()).toBeNull()
        second.unmount()
        localStorage.clear()
        render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(20_000)
        fireEvent.click(screen.getByRole("button", { name: "Dismiss community news" }))
        expect(prompt()).toBeNull()
        expect(localStorage.getItem(COMMUNITY_NEWS_KEY)).toBe("read")
    })
    it("keeps public links in News and suppresses a later automatic prompt when read", () => {
        render(<><CommunityNewsPrompt enabled openNews={vi.fn()} /><CommunityNews /></>)
        advance(30_000)
        expect(prompt()).toBeNull()
        expect(screen.getByRole("link", { name: /Follow on X/ })).toHaveAttribute("href", "https://x.com/membaclub")
        const telegram = screen.getByRole("link", { name: /Join Telegram/ })
        expect(telegram).toHaveAttribute("href", "https://t.me/+t0xM6gipZcZhNWQ0")
        expect(telegram).toHaveAttribute("target", "_blank")
        expect(telegram).toHaveAttribute("rel", "noopener noreferrer")
    })
    it("does not mark a background News window read, and opens News from the card", () => {
        const open = vi.fn()
        render(<><CommunityNewsPrompt enabled openNews={open} /><CommunityNews active={false} /></>)
        advance(20_000)
        expect(prompt()).toBeVisible()
        fireEvent.click(screen.getByRole("button", { name: "Read in News" }))
        expect(open).toHaveBeenCalledOnce()
        expect(prompt()).toBeNull()
    })
    it("cancels the timer on phones, boot/lock/connect/Meet, and while transactions are pending", () => {
        const view = render(<CommunityNewsPrompt enabled={false} openNews={vi.fn()} />)
        advance(60_000)
        expect(prompt()).toBeNull()
        vi.mocked(useSigner).mockReturnValue({ pending: [{ id: 1, label: "Signing" }] } as never)
        view.rerender(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(60_000)
        expect(prompt()).toBeNull()
        vi.mocked(useSigner).mockReturnValue({ pending: [] } as never)
        view.rerender(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(19_999)
        expect(prompt()).toBeNull()
        view.unmount()
        advance(1)
        expect(localStorage.getItem(COMMUNITY_NEWS_KEY)).toBeNull()
    })
    it("hides a presented card while signing and honours a read in another tab", () => {
        const view = render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(20_000)
        expect(prompt()).toBeVisible()
        vi.mocked(useSigner).mockReturnValue({ pending: [{ id: 1, label: "Signing" }] } as never)
        view.rerender(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        expect(prompt()).toBeNull()
        vi.mocked(useSigner).mockReturnValue({ pending: [] } as never)
        view.rerender(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        expect(prompt()).toBeVisible()
        act(() => {
            localStorage.setItem(COMMUNITY_NEWS_KEY, "read")
            window.dispatchEvent(new StorageEvent("storage", { key: COMMUNITY_NEWS_KEY }))
        })
        expect(prompt()).toBeNull()
    })
    it("defers and hides immediately from wallet review through the wallet decision", () => {
        render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        let end = () => {}
        try {
            act(() => { end = beginWalletActivity() })
            advance(30_000)
            expect(prompt()).toBeNull()
            act(() => end())
            advance(20_000)
            expect(prompt()).toBeVisible()
            act(() => { end = beginWalletActivity() })
            expect(prompt()).toBeNull()
            act(() => end())
            expect(prompt()).toBeVisible()
            fireEvent.click(screen.getByRole("button", { name: "Dismiss community news" }))
            advance(30_000)
            expect(prompt()).toBeNull()
        } finally { act(() => end()) }
    })
    it("waits for the foreground tab, signing review and two seconds without input", () => {
        vi.spyOn(document, "hidden", "get").mockReturnValue(true)
        render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        const modal = document.createElement("div")
        modal.setAttribute("aria-modal", "true")
        document.body.append(modal)
        advance(20_000)
        expect(prompt()).toBeNull()
        vi.spyOn(document, "hidden", "get").mockReturnValue(false)
        advance(1_000)
        expect(prompt()).toBeNull()
        modal.remove()
        fireEvent.keyDown(window, { key: "a" })
        advance(1_000)
        expect(prompt()).toBeNull()
        advance(1_000)
        expect(prompt()).toBeVisible()
    })
    it("avoids automatic prompts when durable storage cannot be read or written", () => {
        vi.stubGlobal("localStorage", { getItem: () => { throw new Error("blocked") } })
        const first = render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(30_000)
        expect(prompt()).toBeNull()
        first.unmount()
        vi.stubGlobal("localStorage", { getItem: () => null, setItem: () => { throw new Error("blocked") } })
        const second = render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(30_000)
        expect(prompt()).toBeNull()
        second.unmount()
        vi.unstubAllGlobals()
        render(<CommunityNewsPrompt enabled openNews={vi.fn()} />)
        advance(20_000)
        expect(prompt()).toBeVisible()
        // A browser can refuse subsequent writes even though presentation was saved.
        vi.stubGlobal("localStorage", { getItem: () => "shown", setItem: () => { throw new Error("blocked") } })
        fireEvent.click(screen.getByRole("button", { name: "Dismiss community news" }))
        expect(prompt()).toBeNull()
    })
})
