/** Cinema storefront kit: the dark, cover-first building blocks of the Arcade and App Store windows. */
export { CinemaShell, CinemaScope } from "./CinemaShell"
export { AppIcon } from "./AppIcon"
export { monogram } from "./monogram"
export { RatingBadge } from "./RatingBadge"
export { CoverCapsule, type CapsuleProps } from "./CoverCapsule"
export { HeroCarousel, type HeroSlide } from "./HeroCarousel"
export { Shelf } from "./Shelf"
export { MediaGallery } from "./MediaGallery"
export { DetailLayout } from "./DetailLayout"
export { InfoRows } from "./InfoRows"
export { useReviewSummaries } from "./useReviewSummaries"
