#!/usr/bin/env bash
# Regenerate the TypeScript ABI files the frontend imports.
#
# These are generated artifacts checked into the repo. They drifted silently once
# already: 13 of 15 went stale after a round of contract changes, so the frontend
# would have been encoding calls against a contract shape that no longer existed —
# and nothing failed, because nothing compared them. CI now runs this and fails on a
# diff (see .github/workflows/evm.yml).
#
# Usage: contracts/evm/script/gen-abis.sh   (from the repo root)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
OUT="$ROOT/frontend/src/lib/chain/evm/abi"
cd "$ROOT/contracts/evm"

forge build --silent

for contract in MembaDAO MembaCandidature MembaTokenFactory MembaToken MembaEscrow \
                MembaNFT MembaCollections MembaTokenOTC MembaChannels MembaReviews \
                MembaBadges MembaQuests MembaPoints MembaAppStore MembaRegistry; do
  artifact="out/${contract}.sol/${contract}.json"
  if [ ! -f "$artifact" ]; then
    echo "::error::missing artifact for ${contract} — did forge build succeed?" >&2
    exit 1
  fi
  # Command substitution strips the trailing newline, so `as const` lands on the
  # closing bracket rather than on its own line (which is a syntax error).
  abi="$(jq '.abi' "$artifact")"
  {
    printf '/** %s ABI — generated by contracts/evm/script/gen-abis.sh. Do not edit. */\n' "$contract"
    printf 'export const %sABI = %s as const\n' "$contract" "$abi"
  } > "$OUT/${contract}.ts"
done

echo "regenerated 15 ABIs into ${OUT}"
