// Load this entrypoint lazily from Notes; never from the OS bootstrap.
export { NotesCryptoError } from './bytes'
export { MAX_BODY_BYTES, MAX_TITLE_BYTES, MAX_COMMENT_BYTES } from './padding'
export { keyCommitment, sealField, openField } from './content'
export type { EpochContext, FieldContext } from './content'
export { encodeComment, decodeComment } from './comment'
export type { CommentPayload } from './comment'
export { wrapForReader, unwrapForReader, WRAP_BYTES } from './wrap'
export type { ReaderContext } from './wrap'
export { encodeManifest, decodeManifest, MAX_RECIPIENTS } from './manifest'
export type { Recipient } from './manifest'
export { newIdentitySeed, identityFromSeed, verifiedIdentity } from './identity'
export type { NotesIdentity } from './identity'
export { sealBackup, openBackup, parseBackup, recoverIdentity, MAX_BACKUP_BYTES } from './backup'
export type { BackupMode, BackupBinding, ParsedBackup } from './backup'
export { requestNotesUnlock, verifyUnlockResponse, UNLOCK_TEXT } from './signer'
export type { UnlockContext, NotesArbitraryWallet, VerifiedUnlock } from './signer'
export { parseSecretLink, formatSecretLink, createOneTimeLinkReader, verifyLinkEpoch } from './link'
export type { LinkSecret } from './link'
