// GENERATED by frontend/scripts/gen-evm-manifest.mjs from deployments/evm/8453.json, deployments/evm/84532.json. Do not edit:
// change the JSON (checked against the chains by contracts/evm/test/manifest), then run
// `node scripts/gen-evm-manifest.mjs` in frontend/.

export const EVM_MANIFEST = {
    "8453": {
        "network": "base",
        "verified": {
            "date": "2026-10-07",
            "block": 52292042
        },
        "contracts": {
            "safeSingleton": {
                "address": "0xFf51A5898e281Db6DfC7855790607438dF2ca44b",
                "codehash": "0xdda019cbd7c867a533a2a86e5c53434fdc50b13122b5a5ddb4a8df61b31c20f2",
                "version": "1.5.0"
            },
            "safeL2Singleton": {
                "address": "0xEdd160fEBBD92E350D4D398fb636302fccd67C7e",
                "codehash": "0x180193227186ccb85316c94db1f0d156ed932b14712cfaac78901899178572dc",
                "version": "1.5.0"
            },
            "safeProxyFactory": {
                "address": "0x14F2982D601c9458F93bd70B218933A6f8165e7b",
                "codehash": "0x967dae4cda22b0c9ef7f31b010bdc1ceb0af9904b0c3dc060b5302e4c18a4529",
                "version": "1.5.0"
            },
            "safeFallbackHandler": {
                "address": "0x3EfCBb83A4A7AfcB4F68D501E2c2203a38be77f4",
                "codehash": "0x3c6a85bcf7b563daa624b884b4e9a1b9fa5371edde7be945d998071a48f28bbc",
                "version": "1.5.0"
            },
            "safeMultiSend": {
                "address": "0x218543288004CD07832472D464648173c77D7eB7",
                "codehash": "0xca1147a12963172a93910c5cb2bfa5ad0e941c7f03fc7eb017dd06a8ea4e5604",
                "version": "1.5.0"
            },
            "safeMultiSendCallOnly": {
                "address": "0xA83c336B20401Af773B6219BA5027174338D1836",
                "codehash": "0xcdbdcec38d2f1c7d961b0029ff8416b7e86e9974d6f0e9c9580c7d17fcfb6663",
                "version": "1.5.0"
            },
            "safeSingletonFactory": {
                "address": "0x914d7Fec6aaC8cd542e72Bca78B30650d45643d7",
                "codehash": "0x2fa86add0aed31f33a762c9d88e807c475bd51d0f52bd0955754b2608f7e4989"
            },
            "allowanceModuleV1": {
                "address": "0x691f59471Bfd2B7d639DCF74671a2d648ED1E331",
                "codehash": "0xfafc86ce3000fbdc8ad155875c0b3b5a20d17662e7c2cdbf3e95f15945a46657",
                "version": "1.0.0"
            },
            "allowanceModuleV011": {
                "address": "0xAA46724893dedD72658219405185Fb0Fc91e091C",
                "codehash": "0x7aa63affdca06fe94576f00077ad61a02ccf203a5da31e1b4ed595df7b65cf3e",
                "version": "0.1.1"
            },
            "zodiacRolesV2Mastercopy": {
                "address": "0xF2964CE6161ce0e75964Fe7927cE114cb0B283D5",
                "codehash": "0x471d8b3b419f1eb955230c0326c8812176df49bf3c7b414a563fda5a3c6c10b6",
                "version": "2.1.1"
            },
            "zodiacModuleProxyFactory": {
                "address": "0x000000000000aDdB49795b0f9bA5BC298cDda236",
                "codehash": "0x01623cbcf010a1c326230f1b2d5f48a66b440232ee49096102bc84967dc5f21e",
                "version": "1.2.0"
            },
            "zodiacRolesIntegrity": {
                "address": "0x6a6Af4b16458Bc39817e4019fB02BD3b26d41049",
                "codehash": "0xee8ec55ea4ac609a3fc768eccf3f0479631454fe0a802e4a4b8132102d10d495",
                "version": "2.1.1"
            },
            "zodiacRolesPacker": {
                "address": "0x869718C939652084BC491fBC5ce0D3C1d5B309F0",
                "codehash": "0xc28f5fb0c8857669286d01e3df89f310d5ddfbf98205ad46d2f7d28767a76c82",
                "version": "2.1.1"
            },
            "zodiacRolesMultiSendUnwrapper": {
                "address": "0xB4Cd4bb764C089f20DA18700CE8bc5e49F369efD",
                "codehash": "0x1f6e088be5e6ef9d0fbe0547d3fa9a9e40d823433fd8a4449215b5663209a1eb",
                "version": "2.1.1"
            },
            "snapshotXProxyFactory": {
                "address": "0x4B4F7f64Be813Ccc66AEFC3bFCe2baA01188631c",
                "codehash": "0x9d58d183bb98c199c270f0f2ba7c0abbda1a119caef4c136e137bbacca8c4035"
            },
            "snapshotXSpaceImpl": {
                "address": "0xC3031A7d3326E47D49BfF9D374d74f364B29CE4D",
                "codehash": "0x4f2f90c70374b7dcd468d351747e9c865efc0d47e606eb6fdaeb2a842c148d81"
            },
            "snapshotXWhitelistVoting": {
                "address": "0x3CEE21A33751A2722413fF62dEC3dEc48e7748A4",
                "codehash": "0x5ac5acac888dd781c9cfe7cdac9182a316560bfc6aa443ee148c0ed090d3d585"
            },
            "snapshotXAvatarExecutionImpl": {
                "address": "0xecE4f6b01a2d7FF5A9765cA44162D453fC455e42",
                "codehash": "0xff49b6b368f46437fcdcca49e92468602a8b2d61da76bbcf2f49652f6bcfb28a"
            },
            "snapshotXTimelockExecutionImpl": {
                "address": "0xf2A1C2f2098161af98b2Cc7E382AB7F3ba86Ebc4",
                "codehash": "0x3865767ce0d582f31812edde45d3909a333fc04e5a1a6f8e1f686d6023a95eed"
            },
            "snapshotXVanillaAuthenticator": {
                "address": "0xb9BE0a0093933968E3B4c4fC5d939B6c1Fe45142",
                "codehash": "0xcc5ac61ffe33da5b76ee182f88f532af0041f693f347341cba4a31732031f108"
            },
            "snapshotXEthTxAuthenticator": {
                "address": "0xBA06E6cCb877C332181A6867c05c8b746A21Aed1",
                "codehash": "0xe7a216f07f812245a89909f0eee52435d9892c029d23dde2e7d46f28a1983bdb"
            },
            "snapshotXEthSigAuthenticator": {
                "address": "0x95CF9B585fDb12DeB78002B5643dFF8fe67a496D",
                "codehash": "0xc2c4b1c07072a071c6a341f0b81a8f73f560e673b54fc9f73838eaee7dfa1814"
            },
            "snapshotXVanillaProposalValidation": {
                "address": "0x9A39194F870c410633C170889E9025fba2113c79",
                "codehash": "0xddd4560ead7f2c3de35f37de8d50c43e57f0173ad3eefd20098c3b6e08cba9d8"
            },
            "snapshotXPropositionPowerValidation": {
                "address": "0x6D9d6D08EF6b26348Bd18F1FC8D953696b7cf311",
                "codehash": "0x2be4000dde1953be92dff29da1c0b058d736ac3194fc63ac1ec33bfed24675ab"
            },
            "uniswapCcaFactory": {
                "address": "0x000000001F26a0044BaA66024e7b6599c61963F8",
                "codehash": "0xa1d2a90564f4f63580b25de42efaff92505c254b00fc666f65ab38126cce5cfa",
                "version": "2.1.0"
            },
            "eas": {
                "address": "0x4200000000000000000000000000000000000021",
                "codehash": "0x1f958654ab06a152993e7a0ae7b6dbb0d4b19265cc9337b8789fe1353bd9dc35",
                "version": "1.0.1",
                "proxy": {
                    "implementation": "0xbEb5Fc579115071764c7423A4f12eDde41f106Ed",
                    "implementationCodehash": "0x16b293cd7ed66fa1e03076e5847c59b146a83c187d991c42fe6056b3c1cc0513"
                }
            },
            "easSchemaRegistry": {
                "address": "0x4200000000000000000000000000000000000020",
                "codehash": "0x1f958654ab06a152993e7a0ae7b6dbb0d4b19265cc9337b8789fe1353bd9dc35",
                "version": "1.0.1",
                "proxy": {
                    "implementation": "0x75505a97BD334E7BD3C476893285569C4136Fa0F",
                    "implementationCodehash": "0x020abfe7296543ec2d825b97a9c3fe26d7beea1fbf80de58e0da20e2a6825753"
                }
            },
            "seaport": {
                "address": "0x0000000000000068F116a894984e2DB1123eB395",
                "codehash": "0x2d5cb8553e21a19550413299c05a6493cc606fb0000b5042328a5ba06bfdaf35",
                "version": "1.6"
            },
            "seaportConduitController": {
                "address": "0x00000000F9490004C11Cef243f5400493c00Ad63",
                "codehash": "0x880348b652e7cce91216153a4d0107e70c77b92192f3d7a127ff1f1351961948"
            },
            "create2Deployer": {
                "address": "0x4e59b44847b379578588920cA78FbF26c0B4956C",
                "codehash": "0x2fa86add0aed31f33a762c9d88e807c475bd51d0f52bd0955754b2608f7e4989"
            },
            "permit2": {
                "address": "0x000000000022D473030F116dDEE9F6B43aC78BA3",
                "codehash": "0xa67739abc3ede9dbdc0491636c67d6a14ac07fab9030c3f509b1eb7b11dff8ed"
            },
            "multicall3": {
                "address": "0xcA11bde05977b3631167028862bE2a173976CA11",
                "codehash": "0xd5c15df687b16f2ff992fc8d767b4216323184a2bbc6ee2f9c398c318e770891"
            },
            "aragonDaoFactory": {
                "address": "0xcc602EA573a42eBeC290f33F49D4A87177ebB8d2",
                "codehash": "0xa0bbd977e2c16d930f82ca77c4ac7bb4f09359de1157852494ce8c2c749aee37",
                "version": "1.4.0"
            },
            "aragonPluginSetupProcessor": {
                "address": "0x91a851E9Ed7F2c6d41b15F76e4a88f5A37067cC9",
                "codehash": "0xb014967d0e04e9bddbd4bba6f05dd1debbd4180330449668a90bbfc0af5d29a5"
            },
            "aragonDaoRegistry": {
                "address": "0xeB98a71d69a1e12B62c10368D9dA5364CE0f7178",
                "codehash": "0x1bce65331ab220385d4fe958fc084b4d00226b85e6633941cfb690ad6b0534a6",
                "proxy": {
                    "implementation": "0xB88fE875623E33BFDa76A517e9d5DC2023995f73",
                    "implementationCodehash": "0x69c815694f5d2f88fd5b1b52ecace3f5ee8cdec9813919007e48348b8176c008"
                }
            },
            "aragonPluginRepoRegistry": {
                "address": "0xB5eB5C011827C9F5787ceE3Abc72d247E36a5a0D",
                "codehash": "0x1bce65331ab220385d4fe958fc084b4d00226b85e6633941cfb690ad6b0534a6",
                "proxy": {
                    "implementation": "0x9d4669361461443eB25A29b79C68C8AC906D8cC1",
                    "implementationCodehash": "0x7d8fa2a2ae017a33c080d6e8cf1ea1735863352de4c1a043deda6c36108000f3"
                }
            },
            "aragonMultisigRepo": {
                "address": "0xcDC4b0BC63AEfFf3a7826A19D101406C6322A585",
                "codehash": "0x1bce65331ab220385d4fe958fc084b4d00226b85e6633941cfb690ad6b0534a6",
                "build": {
                    "release": 1,
                    "build": 3
                },
                "proxy": {
                    "implementation": "0x10a9F51c7e163ac2d061eE8EcD72557722126A81",
                    "implementationCodehash": "0xf22977a6dc23c0a44c29d2ab9ea87ab2e3a3b2f0f8ee2331d8dfcc4742c01a0a"
                }
            },
            "aragonTokenVotingRepo": {
                "address": "0x2532570DcFb749A7F976136CC05648ef2a0f60b0",
                "codehash": "0x1bce65331ab220385d4fe958fc084b4d00226b85e6633941cfb690ad6b0534a6",
                "build": {
                    "release": 1,
                    "build": 4
                },
                "proxy": {
                    "implementation": "0x10a9F51c7e163ac2d061eE8EcD72557722126A81",
                    "implementationCodehash": "0xf22977a6dc23c0a44c29d2ab9ea87ab2e3a3b2f0f8ee2331d8dfcc4742c01a0a"
                }
            },
            "basenamesRegistry": {
                "address": "0xB94704422c2a1E396835A571837Aa5AE53285a95",
                "codehash": "0x353bc9548a1b34980e89e32fd9efceb369faaf19594792a2e9168f15e7ff9a47"
            },
            "basenamesBaseRegistrar": {
                "address": "0x03c4738Ee98aE44591e1A4A4F3CaB6641d95DD9a",
                "codehash": "0x1f879417fc3c65a3111bf79ef584f6a2ea353d175526f3bcb29645cc69d11592"
            },
            "basenamesRegistrarController": {
                "address": "0xa7d2607c6BD39Ae9521e514026CBB078405Ab322",
                "codehash": "0x28898dfa35bcd9f32cc2be3d49c0a9e2540ed32d17872376deadb674749352a5",
                "proxy": {
                    "implementation": "0x9ad14968093C5E8C2A8CC86f6868CFEE8C659717",
                    "implementationCodehash": "0xa3cb7eae93cd507c191a9d9ae0b9bab8234a7c8e72cb59547987f9a303160052"
                }
            },
            "basenamesL2Resolver": {
                "address": "0x426fA03fB86E510d0Dd9F70335Cf102a98b10875",
                "codehash": "0xe561198a50395090294eb9ed1995e51d766fcdd52a4f4b6f7b7b0751503d52af",
                "proxy": {
                    "implementation": "0xf74b949f2105178eEEd4Ef35a131715E967337ab",
                    "implementationCodehash": "0xf8023ae402510c6bc569430baf41f9c6a0468fdb2dea97038f24f534087c1a9b"
                }
            },
            "basenamesL2ResolverLegacy": {
                "address": "0xC6d566A56A1aFf6508b41f6c90ff131615583BCD",
                "codehash": "0x0b59e4aef257ba45839c5dd63f9c0e67497c74f3b2095b1f65148e80d58bd402"
            }
        },
        "deny": {
            "basenamesRegistrarControllerLegacy": {
                "address": "0x4cCb0BB02FCABA27e82a56646E81d8c5bC4119a5",
                "reason": "Legacy RegistrarController: no longer a BaseRegistrar controller on Base, register reverts. Use basenamesRegistrarController."
            }
        }
    },
    "84532": {
        "network": "base-sepolia",
        "verified": {
            "date": "2026-10-07",
            "block": 47802573
        },
        "contracts": {
            "safeSingleton": {
                "address": "0xFf51A5898e281Db6DfC7855790607438dF2ca44b",
                "codehash": "0xdda019cbd7c867a533a2a86e5c53434fdc50b13122b5a5ddb4a8df61b31c20f2",
                "version": "1.5.0"
            },
            "safeL2Singleton": {
                "address": "0xEdd160fEBBD92E350D4D398fb636302fccd67C7e",
                "codehash": "0x180193227186ccb85316c94db1f0d156ed932b14712cfaac78901899178572dc",
                "version": "1.5.0"
            },
            "safeProxyFactory": {
                "address": "0x14F2982D601c9458F93bd70B218933A6f8165e7b",
                "codehash": "0x967dae4cda22b0c9ef7f31b010bdc1ceb0af9904b0c3dc060b5302e4c18a4529",
                "version": "1.5.0"
            },
            "safeFallbackHandler": {
                "address": "0x3EfCBb83A4A7AfcB4F68D501E2c2203a38be77f4",
                "codehash": "0x3c6a85bcf7b563daa624b884b4e9a1b9fa5371edde7be945d998071a48f28bbc",
                "version": "1.5.0"
            },
            "safeMultiSend": {
                "address": "0x218543288004CD07832472D464648173c77D7eB7",
                "codehash": "0xca1147a12963172a93910c5cb2bfa5ad0e941c7f03fc7eb017dd06a8ea4e5604",
                "version": "1.5.0"
            },
            "safeMultiSendCallOnly": {
                "address": "0xA83c336B20401Af773B6219BA5027174338D1836",
                "codehash": "0xcdbdcec38d2f1c7d961b0029ff8416b7e86e9974d6f0e9c9580c7d17fcfb6663",
                "version": "1.5.0"
            },
            "safeSingletonFactory": {
                "address": "0x914d7Fec6aaC8cd542e72Bca78B30650d45643d7",
                "codehash": "0x2fa86add0aed31f33a762c9d88e807c475bd51d0f52bd0955754b2608f7e4989"
            },
            "allowanceModuleV1": {
                "address": "0x691f59471Bfd2B7d639DCF74671a2d648ED1E331",
                "codehash": "0xfafc86ce3000fbdc8ad155875c0b3b5a20d17662e7c2cdbf3e95f15945a46657",
                "version": "1.0.0"
            },
            "allowanceModuleV011": {
                "address": "0xAA46724893dedD72658219405185Fb0Fc91e091C",
                "codehash": "0x7aa63affdca06fe94576f00077ad61a02ccf203a5da31e1b4ed595df7b65cf3e",
                "version": "0.1.1"
            },
            "zodiacRolesV2Mastercopy": {
                "address": "0xF2964CE6161ce0e75964Fe7927cE114cb0B283D5",
                "codehash": "0x471d8b3b419f1eb955230c0326c8812176df49bf3c7b414a563fda5a3c6c10b6",
                "version": "2.1.1"
            },
            "zodiacModuleProxyFactory": {
                "address": "0x000000000000aDdB49795b0f9bA5BC298cDda236",
                "codehash": "0x01623cbcf010a1c326230f1b2d5f48a66b440232ee49096102bc84967dc5f21e",
                "version": "1.2.0"
            },
            "zodiacRolesIntegrity": {
                "address": "0x6a6Af4b16458Bc39817e4019fB02BD3b26d41049",
                "codehash": "0xee8ec55ea4ac609a3fc768eccf3f0479631454fe0a802e4a4b8132102d10d495",
                "version": "2.1.1"
            },
            "zodiacRolesPacker": {
                "address": "0x869718C939652084BC491fBC5ce0D3C1d5B309F0",
                "codehash": "0xc28f5fb0c8857669286d01e3df89f310d5ddfbf98205ad46d2f7d28767a76c82",
                "version": "2.1.1"
            },
            "zodiacRolesMultiSendUnwrapper": {
                "address": "0xB4Cd4bb764C089f20DA18700CE8bc5e49F369efD",
                "codehash": "0x1f6e088be5e6ef9d0fbe0547d3fa9a9e40d823433fd8a4449215b5663209a1eb",
                "version": "2.1.1"
            },
            "snapshotXProxyFactory": {
                "address": "0x4B4F7f64Be813Ccc66AEFC3bFCe2baA01188631c",
                "codehash": "0x9d58d183bb98c199c270f0f2ba7c0abbda1a119caef4c136e137bbacca8c4035"
            },
            "snapshotXSpaceImpl": {
                "address": "0xC3031A7d3326E47D49BfF9D374d74f364B29CE4D",
                "codehash": "0x4f2f90c70374b7dcd468d351747e9c865efc0d47e606eb6fdaeb2a842c148d81"
            },
            "snapshotXWhitelistVoting": {
                "address": "0x3CEE21A33751A2722413fF62dEC3dEc48e7748A4",
                "codehash": "0x5ac5acac888dd781c9cfe7cdac9182a316560bfc6aa443ee148c0ed090d3d585"
            },
            "snapshotXAvatarExecutionImpl": {
                "address": "0xecE4f6b01a2d7FF5A9765cA44162D453fC455e42",
                "codehash": "0xff49b6b368f46437fcdcca49e92468602a8b2d61da76bbcf2f49652f6bcfb28a"
            },
            "snapshotXTimelockExecutionImpl": {
                "address": "0xf2A1C2f2098161af98b2Cc7E382AB7F3ba86Ebc4",
                "codehash": "0x3865767ce0d582f31812edde45d3909a333fc04e5a1a6f8e1f686d6023a95eed"
            },
            "snapshotXVanillaAuthenticator": {
                "address": "0xb9BE0a0093933968E3B4c4fC5d939B6c1Fe45142",
                "codehash": "0xcc5ac61ffe33da5b76ee182f88f532af0041f693f347341cba4a31732031f108"
            },
            "snapshotXEthTxAuthenticator": {
                "address": "0xBA06E6cCb877C332181A6867c05c8b746A21Aed1",
                "codehash": "0xe7a216f07f812245a89909f0eee52435d9892c029d23dde2e7d46f28a1983bdb"
            },
            "snapshotXEthSigAuthenticator": {
                "address": "0x95CF9B585fDb12DeB78002B5643dFF8fe67a496D",
                "codehash": "0x908f830614f145bf3820834e16985efffd940dc2d5e285fcc0dfb96ce2aa5d75"
            },
            "snapshotXVanillaProposalValidation": {
                "address": "0x9A39194F870c410633C170889E9025fba2113c79",
                "codehash": "0xddd4560ead7f2c3de35f37de8d50c43e57f0173ad3eefd20098c3b6e08cba9d8"
            },
            "snapshotXPropositionPowerValidation": {
                "address": "0x6D9d6D08EF6b26348Bd18F1FC8D953696b7cf311",
                "codehash": "0x2be4000dde1953be92dff29da1c0b058d736ac3194fc63ac1ec33bfed24675ab"
            },
            "uniswapCcaFactory": {
                "address": "0x000000001F26a0044BaA66024e7b6599c61963F8",
                "codehash": "0xa1d2a90564f4f63580b25de42efaff92505c254b00fc666f65ab38126cce5cfa",
                "version": "2.1.0"
            },
            "eas": {
                "address": "0x4200000000000000000000000000000000000021",
                "codehash": "0xfa8c9db6c6cab7108dea276f4cd09d575674eb0852c0fa3187e59e98ef977998",
                "version": "1.2.0",
                "proxy": {
                    "implementation": "0xC0D3c0D3C0d3c0D3c0D3C0D3c0D3c0d3c0d30021",
                    "implementationCodehash": "0x703f246f804f8d4b315fd7b5fc504671f726230373571e02b69794d0f2614fd7"
                }
            },
            "easSchemaRegistry": {
                "address": "0x4200000000000000000000000000000000000020",
                "codehash": "0xfa8c9db6c6cab7108dea276f4cd09d575674eb0852c0fa3187e59e98ef977998",
                "version": "1.2.0",
                "proxy": {
                    "implementation": "0xc0d3c0d3c0d3C0d3c0d3C0D3C0D3c0d3C0D30020",
                    "implementationCodehash": "0x4f01862031e523fc22a2bbe86c670a2f57f0da57ce1f582b0776042290377672"
                }
            },
            "seaport": {
                "address": "0x0000000000000068F116a894984e2DB1123eB395",
                "codehash": "0x7912af42062ec0080cde88360c1429d58984ae16eb3f17af505b815bf6ffc745",
                "version": "1.6"
            },
            "seaportConduitController": {
                "address": "0x00000000F9490004C11Cef243f5400493c00Ad63",
                "codehash": "0x880348b652e7cce91216153a4d0107e70c77b92192f3d7a127ff1f1351961948"
            },
            "create2Deployer": {
                "address": "0x4e59b44847b379578588920cA78FbF26c0B4956C",
                "codehash": "0x2fa86add0aed31f33a762c9d88e807c475bd51d0f52bd0955754b2608f7e4989"
            },
            "permit2": {
                "address": "0x000000000022D473030F116dDEE9F6B43aC78BA3",
                "codehash": "0xdcde65555316946c298e4c60c6213eb5c3aeab4354d1f3fac5427236bcbb9ebe"
            },
            "multicall3": {
                "address": "0xcA11bde05977b3631167028862bE2a173976CA11",
                "codehash": "0xd5c15df687b16f2ff992fc8d767b4216323184a2bbc6ee2f9c398c318e770891"
            },
            "aragonDaoFactory": {
                "address": "0x016CBa9bd729C30b16849b2c52744447767E9dab",
                "codehash": "0x0df48db198643ea62e7cc254523fd10b45693642cf6aa54d7352dd79d3ef7860",
                "version": "1.4.0"
            },
            "aragonPluginSetupProcessor": {
                "address": "0xd97D409Ca645b108468c26d8506f3a4Bf9D0BE81",
                "codehash": "0xfcb47ca000a871dcafc9c8a8cd6065f9490467c69934c07708880380251d0609"
            },
            "aragonDaoRegistry": {
                "address": "0xea14d8f9e029f666E247955E0fA25A1a1e236a50",
                "codehash": "0x08349d5a38235748c9496d25a57f4bc8e6793e452e5f7b10903ec48d1ab8c74c",
                "proxy": {
                    "implementation": "0xe70a46af77a1d0bc85dC16Adb1Ea1148ce483b06",
                    "implementationCodehash": "0x7765cdfd4806e473960d256d33463be2017e5b001c530446c76fb28a16cc2f32"
                }
            },
            "aragonPluginRepoRegistry": {
                "address": "0xd22e93292A02140957CD0217b317140B1388CE23",
                "codehash": "0x08349d5a38235748c9496d25a57f4bc8e6793e452e5f7b10903ec48d1ab8c74c",
                "proxy": {
                    "implementation": "0x5dEf73A4A6d7976A298f3669FA5926BaFc8c18Aa",
                    "implementationCodehash": "0x7ea2220d387732af43bd4a51e9af7e8564c7279d2fd21f4a1ddf21110eb8033c"
                }
            },
            "aragonMultisigRepo": {
                "address": "0x705596219C1C31dd92E3449c8E04251CcacCb6aB",
                "codehash": "0x08349d5a38235748c9496d25a57f4bc8e6793e452e5f7b10903ec48d1ab8c74c",
                "build": {
                    "release": 1,
                    "build": 3
                },
                "proxy": {
                    "implementation": "0x3BA78469FfD1AB019566EAee768cc99d2a6b6Be7",
                    "implementationCodehash": "0xdbc6ce82ac07736d46972c7f9cfd87d79164732d1def71c2ed01abf057446321"
                }
            },
            "aragonTokenVotingRepo": {
                "address": "0xdEbcF8779495a62156c6d1416628F60525984e9d",
                "codehash": "0x08349d5a38235748c9496d25a57f4bc8e6793e452e5f7b10903ec48d1ab8c74c",
                "build": {
                    "release": 1,
                    "build": 3
                },
                "proxy": {
                    "implementation": "0x3BA78469FfD1AB019566EAee768cc99d2a6b6Be7",
                    "implementationCodehash": "0xdbc6ce82ac07736d46972c7f9cfd87d79164732d1def71c2ed01abf057446321"
                }
            },
            "basenamesRegistry": {
                "address": "0x1493b2567056c2181630115660963E13A8E32735",
                "codehash": "0x353bc9548a1b34980e89e32fd9efceb369faaf19594792a2e9168f15e7ff9a47"
            },
            "basenamesBaseRegistrar": {
                "address": "0xA0c70ec36c010B55E3C434D6c6EbEEC50c705794",
                "codehash": "0xd34980744a10c7c697040eab4217c4f898eff2e368f5a13a3730c00871d6354d"
            },
            "basenamesRegistrarController": {
                "address": "0x82c858CDF64b3D893Fe54962680edFDDC37e94C8",
                "codehash": "0x59c6d41167b7183daba3411654e04c6a17d9393723464656526df6bc84917de7",
                "proxy": {
                    "implementation": "0xb53e99F4a96dce67E772038a32aBd1131E216770",
                    "implementationCodehash": "0xa3cb7eae93cd507c191a9d9ae0b9bab8234a7c8e72cb59547987f9a303160052"
                }
            },
            "basenamesL2Resolver": {
                "address": "0x85C87e548091f204C2d0350b39ce1874f02197c6",
                "codehash": "0x519955142f4f6a53016c77bde296ebf6702988de491c85a9c9c1c99a16346ca5",
                "proxy": {
                    "implementation": "0xC014B9c02b0EDeA17255Ce019e6ab6c24E4AD073",
                    "implementationCodehash": "0xf8023ae402510c6bc569430baf41f9c6a0468fdb2dea97038f24f534087c1a9b"
                }
            },
            "basenamesL2ResolverLegacy": {
                "address": "0x6533C94869D28fAA8dF77cc63f9e2b2D6Cf77eBA",
                "codehash": "0x5f8138cfb4afbb24152621c1f656f631680d2670dee017eec534b13aec50efc2"
            }
        },
        "deny": {
            "basenamesRegistrarControllerLegacy": {
                "address": "0x49aE3cC2e3AA768B1e5654f5D3C6002144A59581",
                "reason": "Legacy RegistrarController: still accepted on Base Sepolia only, refused on Base. A testnet-only success trap. Use basenamesRegistrarController."
            },
            "aragonTokenVotingRepoNpm": {
                "address": "0x424F4cA6FA9c24C03f2396DF0E96057eD11CF7dF",
                "reason": "Stale TokenVoting repo (build 2) listed in the plugin npm addresses.json. Use aragonTokenVotingRepo (osx-commons)."
            }
        }
    }
} as const
