/**
 * GnoloveAIReports — Weekly AI-generated ecosystem reports.
 *
 * Displays Mistral-powered summaries of Gno ecosystem activity,
 * grouped by project with stylized narrative descriptions.
 *
 * @module pages/gnolove/GnoloveAIReports
 */

import { useState, useMemo, useCallback } from "react"
import { useGnoloveAIReports } from "../../hooks/gnolove"
import type { TAIReport } from "../../lib/gnoloveSchemas"

function formatDate(iso: string): string {
    try {
        return new Date(iso).toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
        })
    } catch {
        return iso
    }
}

function reportToMarkdown(report: TAIReport): string {
    const projects = report.data?.projects ?? []
    const lines = [
        `# Weekly Ecosystem Report — ${formatDate(report.createdAt)}`,
        "",
        ...projects.flatMap(p => [`## ${p.project_name}`, "", p.summary, ""]),
        `_Generated by gnolove AI on ${report.createdAt.slice(0, 10)}_`,
    ]
    return lines.join("\n")
}

function downloadMarkdown(report: TAIReport) {
    const md = reportToMarkdown(report)
    const blob = new Blob([md], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `gnolove-ai-report-${report.createdAt.slice(0, 10)}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
}

function ReportCard({ report }: { report: TAIReport }) {
    const projects = report.data?.projects ?? []
    const [copied, setCopied] = useState(false)

    const handleCopy = useCallback(() => {
        navigator.clipboard.writeText(reportToMarkdown(report)).then(() => {
            setCopied(true)
            setTimeout(() => setCopied(false), 1500)
        })
    }, [report])

    return (
        <div className="gl-panel" style={{ marginBottom: 16 }}>
            <div className="gl-panel-header" style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <h3 className="gl-panel-title">
                    {formatDate(report.createdAt)}
                </h3>
                <div style={{ display: "flex", gap: 6 }}>
                    <button className="gl-export-btn" onClick={handleCopy} style={{ fontSize: 11, padding: "3px 8px" }}>
                        {copied ? "Copied!" : "Copy"}
                    </button>
                    <button className="gl-export-btn" onClick={() => downloadMarkdown(report)} style={{ fontSize: 11, padding: "3px 8px" }}>
                        Download MD
                    </button>
                </div>
            </div>
            {projects.length === 0 ? (
                <p className="gl-empty-text">No project data in this report.</p>
            ) : (
                <div style={{ display: "flex", flexDirection: "column", gap: 12, padding: "12px 0" }}>
                    {projects.map((p, i) => (
                        <div key={i} style={{ padding: "0 16px" }}>
                            <h4 style={{ fontSize: 13, fontWeight: 600, marginBottom: 4, color: "#a78bfa" }}>
                                {p.project_name}
                            </h4>
                            <p style={{ fontSize: 12, lineHeight: 1.6, color: "var(--color-text-secondary)", margin: 0 }}>
                                {p.summary}
                            </p>
                        </div>
                    ))}
                </div>
            )}
        </div>
    )
}

export default function GnoloveAIReports() {
    const { data: reports, isLoading } = useGnoloveAIReports()
    const [visibleCount, setVisibleCount] = useState(5)

    const sortedReports = useMemo(() => {
        if (!reports?.length) return []
        return [...reports].sort(
            (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
        )
    }, [reports])

    const visibleReports = sortedReports.slice(0, visibleCount)

    if (isLoading) {
        return (
            <div className="gl-loading">
                <div className="gl-skeleton" />
                <div className="gl-skeleton" />
                <div className="gl-skeleton" />
            </div>
        )
    }

    if (!sortedReports.length) {
        return (
            <div className="gl-empty">
                <p>No AI reports available yet.</p>
                <p style={{ fontSize: 12, color: "var(--color-text-secondary)" }}>
                    Reports are generated weekly by the gnolove backend.
                </p>
            </div>
        )
    }

    return (
        <div className="gl-page">
            <div className="gl-header">
                <h1 className="gl-title">AI Reports</h1>
                <p className="gl-subtitle">
                    Weekly AI-generated ecosystem summaries ({sortedReports.length} reports)
                </p>
            </div>

            {visibleReports.map((report) => (
                <ReportCard key={report.id} report={report} />
            ))}

            {visibleCount < sortedReports.length && (
                <button
                    className="gl-filter-btn gl-filter-btn--active"
                    style={{ margin: "16px auto", display: "block" }}
                    onClick={() => setVisibleCount((c) => c + 5)}
                >
                    Load more ({sortedReports.length - visibleCount} remaining)
                </button>
            )}
        </div>
    )
}
