/**
 * GnoloveAIReports — Weekly AI-generated ecosystem reports.
 *
 * Displays Mistral-powered summaries of Gno ecosystem activity,
 * grouped by project with stylized narrative descriptions.
 *
 * @module pages/gnolove/GnoloveAIReports
 */

import { useState, useMemo, useCallback, useEffect, useRef } from "react"
import { useSearchParams } from "react-router-dom"
import { useGnoloveAIReports } from "../../hooks/gnolove"
import type { TAIReport } from "../../lib/gnoloveSchemas"
import { PageMeta } from "../../components/gnolove/PageMeta"

function formatDate(iso: string): string {
    try {
        return new Date(iso).toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
        })
    } catch {
        return iso
    }
}

function reportToMarkdown(report: TAIReport): string {
    const projects = report.data?.projects ?? []
    const lines = [
        `# Weekly Ecosystem Report — ${formatDate(report.createdAt)}`,
        "",
        ...projects.flatMap(p => [`## ${p.project_name}`, "", p.summary, ""]),
        `_Generated by gnolove AI on ${report.createdAt.slice(0, 10)}_`,
    ]
    return lines.join("\n")
}

function downloadMarkdown(report: TAIReport) {
    const md = reportToMarkdown(report)
    const blob = new Blob([md], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `gnolove-ai-report-${report.createdAt.slice(0, 10)}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
}

function ReportCard({ report, highlighted, refSetter }: {
    report: TAIReport
    highlighted: boolean
    refSetter?: (el: HTMLDivElement | null) => void
}) {
    const projects = report.data?.projects ?? []
    const [copied, setCopied] = useState(false)
    const [linkCopied, setLinkCopied] = useState(false)

    const handleCopy = useCallback(() => {
        navigator.clipboard.writeText(reportToMarkdown(report)).then(() => {
            setCopied(true)
            setTimeout(() => setCopied(false), 1500)
        })
    }, [report])

    const handleCopyLink = useCallback(() => {
        const url = `${window.location.origin}${window.location.pathname}?id=${encodeURIComponent(report.id)}`
        navigator.clipboard.writeText(url).then(() => {
            setLinkCopied(true)
            setTimeout(() => setLinkCopied(false), 1500)
        })
    }, [report.id])

    return (
        <div
            ref={refSetter}
            className={`gl-panel${highlighted ? " gl-panel--highlight" : ""}`}
            style={{ marginBottom: 16 }}
            data-report-id={report.id}
        >
            <div className="gl-panel-header" style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <h3 className="gl-panel-title">
                    {formatDate(report.createdAt)}
                </h3>
                <div style={{ display: "flex", gap: 6 }}>
                    <button
                        className="gl-export-btn"
                        onClick={handleCopyLink}
                        style={{ fontSize: 11, padding: "3px 8px" }}
                        aria-label={`Copy permalink to report from ${formatDate(report.createdAt)}`}
                    >
                        {linkCopied ? "✓ Linked" : "🔗 Link"}
                    </button>
                    <button className="gl-export-btn" onClick={handleCopy} style={{ fontSize: 11, padding: "3px 8px" }}>
                        {copied ? "Copied!" : "Copy"}
                    </button>
                    <button className="gl-export-btn" onClick={() => downloadMarkdown(report)} style={{ fontSize: 11, padding: "3px 8px" }}>
                        Download MD
                    </button>
                </div>
            </div>
            {projects.length === 0 ? (
                <p className="gl-empty-text">No project data in this report.</p>
            ) : (
                <div style={{ display: "flex", flexDirection: "column", gap: 12, padding: "12px 0" }}>
                    {projects.map((p, i) => (
                        <div key={i} style={{ padding: "0 16px" }}>
                            <h4 style={{ fontSize: 13, fontWeight: 600, marginBottom: 4, color: "#a78bfa" }}>
                                {p.project_name}
                            </h4>
                            <p style={{ fontSize: 12, lineHeight: 1.6, color: "var(--color-text-secondary)", margin: 0 }}>
                                {p.summary}
                            </p>
                        </div>
                    ))}
                </div>
            )}
        </div>
    )
}

export default function GnoloveAIReports() {
    const { data: reports, isLoading } = useGnoloveAIReports()
    const [baseVisibleCount, setBaseVisibleCount] = useState(5)
    const [searchParams] = useSearchParams()
    const targetId = searchParams.get("id")
    const targetRef = useRef<HTMLDivElement | null>(null)

    const sortedReports = useMemo(() => {
        if (!reports?.length) return []
        return [...reports].sort(
            (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
        )
    }, [reports])

    // Effective visible count auto-expands to include the deep-linked target if it's
    // below the user's current "load more" cutoff. Pure computation — no setState in effect.
    const effectiveVisibleCount = useMemo(() => {
        if (!targetId || sortedReports.length === 0) return baseVisibleCount
        const idx = sortedReports.findIndex(r => r.id === targetId)
        return idx >= 0 ? Math.max(baseVisibleCount, idx + 1) : baseVisibleCount
    }, [targetId, sortedReports, baseVisibleCount])

    // Scroll-into-view on mount when ?id= is present.
    useEffect(() => {
        if (!targetId || !targetRef.current) return
        const el = targetRef.current
        const handle = window.requestAnimationFrame(() => {
            el.scrollIntoView({ behavior: "smooth", block: "center" })
        })
        return () => window.cancelAnimationFrame(handle)
    }, [targetId, sortedReports.length])

    const visibleReports = sortedReports.slice(0, effectiveVisibleCount)

    if (isLoading) {
        return (
            <div className="gl-loading">
                <div className="gl-skeleton" />
                <div className="gl-skeleton" />
                <div className="gl-skeleton" />
            </div>
        )
    }

    if (!sortedReports.length) {
        return (
            <div className="gl-empty">
                <p>No AI reports available yet.</p>
                <p style={{ fontSize: 12, color: "var(--color-text-secondary)" }}>
                    Reports are generated weekly by the gnolove backend.
                </p>
            </div>
        )
    }

    return (
        <div className="gl-page">
            <PageMeta title="AI Reports | Gnolove · Memba" description="Weekly AI-generated ecosystem summaries for the Gno ecosystem." />
            <div className="gl-header">
                <h1 className="gl-title">AI Reports</h1>
                <p className="gl-subtitle">
                    Weekly AI-generated ecosystem summaries ({sortedReports.length} reports)
                </p>
            </div>

            {visibleReports.map((report) => (
                <ReportCard
                    key={report.id}
                    report={report}
                    highlighted={report.id === targetId}
                    refSetter={report.id === targetId ? (el) => { targetRef.current = el } : undefined}
                />
            ))}

            {effectiveVisibleCount < sortedReports.length && (
                <button
                    className="gl-filter-btn gl-filter-btn--active"
                    style={{ margin: "16px auto", display: "block" }}
                    onClick={() => setBaseVisibleCount((c) => c + 5)}
                >
                    Load more ({sortedReports.length - effectiveVisibleCount} remaining)
                </button>
            )}
        </div>
    )
}
