/**
 * AIReportCard — shared component for one AI weekly report.
 *
 * Replaces the inline ReportCard in pages/gnolove/GnoloveAIReports.tsx and
 * the project-row block in components/gnolove/teams/TeamHubAIReportsCard.tsx.
 *
 * Phase 5 additions over the Phase 4 first cut:
 *   - Short/long inline toggle per project, with a "Read Detailed Report"
 *     label (operator decision Q-3). Empty strings fall back to the legacy
 *     `summary` via `||` (plan R-8 — never `??`).
 *   - On viewports under {@link MOBILE_BREAKPOINT_PX}, the long view opens
 *     as a bottom sheet instead of expanding inline. Detected at mount with
 *     a window-listener so resizes are reactive.
 *   - Optional `teamSlug` filters projects to those tagged with that team
 *     (prompt v2 `team` field). Falls back to "show all" when no project
 *     in the report carries a team tag — keeps v1 rollover usable.
 *
 * @module components/gnolove/AIReportCard
 */

import { useCallback, useEffect, useState } from "react"
import type { TAIReport, TAIReportProject } from "../../lib/gnoloveSchemas"

const MOBILE_BREAKPOINT_PX = 768

interface Props {
    report: TAIReport
    /** When set, render only the projects tagged with this slug. */
    teamSlug?: string
    /** Highlight visually (deep-link target). */
    highlighted?: boolean
    /** Ref-setter so callers can scroll-into-view a deep-linked report. */
    refSetter?: (el: HTMLDivElement | null) => void
    /** Which URL param to use in the copy-link button. Defaults to "aiReport". */
    permalinkParam?: "aiReport" | "id"
    /** Hide the per-card chrome (copy/download/link buttons). Used by the team-hub embed. */
    compact?: boolean
}

function formatDate(iso: string): string {
    try {
        return new Date(iso).toLocaleDateString("en-US", {
            year: "numeric", month: "long", day: "numeric",
        })
    } catch {
        return iso
    }
}

function reportToMarkdown(report: TAIReport): string {
    const projects = report.data?.projects ?? []
    const lines = [
        `# Weekly Ecosystem Report — ${formatDate(report.createdAt)}`,
        "",
        ...projects.flatMap(p => [`## ${p.project_name}`, "", longestText(p), ""]),
        `_Generated by gnolove AI on ${report.createdAt.slice(0, 10)}_`,
    ]
    return lines.join("\n")
}

/** Picks the most informative variant for export. Empty-string-safe (R-8). */
function longestText(p: TAIReportProject): string {
    return p.summary_long || p.summary || p.summary_short || ""
}

function downloadMarkdown(report: TAIReport) {
    const blob = new Blob([reportToMarkdown(report)], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `gnolove-ai-report-${report.createdAt.slice(0, 10)}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
}

function filterByTeam(projects: TAIReportProject[], slug: string | undefined): TAIReportProject[] {
    if (!slug) return projects
    const tagged = projects.some(p => typeof p.team === "string" && p.team.length > 0)
    if (!tagged) return projects // v1 rollover — no team tags → show all
    const want = slug.toLowerCase()
    return projects.filter(p => (p.team ?? "").toLowerCase() === want)
}

/**
 * Slugify a project name for the URL hash. Plan §2 deep-link shape is
 * `?aiReport=<cycle>#<project_name>` — we map the visible name to a stable
 * ASCII slug so the anchor is URL-safe and matches `id={projectAnchor(name)}`.
 */
export function projectAnchor(name: string): string {
    return name
        .toLowerCase()
        .normalize("NFKD")
        .replace(/[^\w\s-]/g, "")
        .trim()
        .replace(/\s+/g, "-")
}

/** Read the current URL hash, stripped of the leading `#`. */
function currentHash(): string {
    if (typeof window === "undefined") return ""
    return decodeURIComponent(window.location.hash.replace(/^#/, ""))
}

function useIsMobile(): boolean {
    const [isMobile, setIsMobile] = useState(() =>
        typeof window !== "undefined" && window.innerWidth < MOBILE_BREAKPOINT_PX,
    )
    useEffect(() => {
        if (typeof window === "undefined") return
        const onResize = () => setIsMobile(window.innerWidth < MOBILE_BREAKPOINT_PX)
        window.addEventListener("resize", onResize)
        return () => window.removeEventListener("resize", onResize)
    }, [])
    return isMobile
}

function ProjectRow({ project, isMobile }: { project: TAIReportProject; isMobile: boolean }) {
    const [expanded, setExpanded] = useState(false)
    const [highlighted, setHighlighted] = useState(false)
    // R-8 explicitly: use `||`, NOT `??`, to drop empty strings.
    const shortText = project.summary_short || project.summary
    const longText = project.summary_long || project.summary
    const hasDistinctLong = longText && longText !== shortText
    const showLongAsSheet = isMobile && expanded && hasDistinctLong
    const showLongInline = !isMobile && expanded && hasDistinctLong

    const anchor = projectAnchor(project.project_name)

    // Plan §2 deep-link: `?aiReport=<id>#<project_name>` should scroll to the
    // matching ProjectRow and auto-expand it. Reacts to hashchange too so the
    // operator's "Copy link" (future) doesn't require a page reload to work.
    useEffect(() => {
        if (typeof window === "undefined") return
        const onHash = () => {
            if (currentHash() === anchor) {
                setExpanded(true)
                setHighlighted(true)
                setTimeout(() => setHighlighted(false), 1500)
                // Scroll into view if the browser hasn't already done so —
                // hashes set after first paint don't auto-scroll on every browser.
                const el = document.getElementById(`gl-aircard-project-${anchor}`)
                el?.scrollIntoView({ behavior: "smooth", block: "start" })
            }
        }
        onHash()
        window.addEventListener("hashchange", onHash)
        return () => window.removeEventListener("hashchange", onHash)
    }, [anchor])

    return (
        <div
            id={`gl-aircard-project-${anchor}`}
            className={`gl-aircard-project${highlighted ? " gl-aircard-project--highlight" : ""}`}
            data-project-anchor={anchor}
        >
            <div className="gl-aircard-project-head">
                <h4 className="gl-aircard-project-name">{project.project_name}</h4>
                {project.team && (
                    <span className="gl-thub-chip gl-aircard-project-team">{project.team}</span>
                )}
            </div>

            <p className="gl-aircard-project-summary">
                {showLongInline ? longText : shortText}
            </p>

            {hasDistinctLong && (
                <button
                    type="button"
                    className="gl-aircard-toggle"
                    onClick={() => setExpanded(v => !v)}
                    aria-expanded={expanded}
                >
                    {expanded ? "Show short summary" : "Read Detailed Report"}
                </button>
            )}

            {showLongAsSheet && (
                <div
                    className="gl-aircard-sheet-backdrop"
                    role="dialog"
                    aria-modal="true"
                    onClick={() => setExpanded(false)}
                >
                    <div
                        className="gl-aircard-sheet"
                        onClick={e => e.stopPropagation()}
                    >
                        <div className="gl-aircard-sheet-head">
                            <h4 className="gl-aircard-project-name">{project.project_name}</h4>
                            <button
                                type="button"
                                className="gl-aircard-sheet-close"
                                onClick={() => setExpanded(false)}
                                aria-label="Close"
                            >
                                ×
                            </button>
                        </div>
                        <p className="gl-aircard-sheet-body">{longText}</p>
                    </div>
                </div>
            )}
        </div>
    )
}

export function AIReportCard({
    report,
    teamSlug,
    highlighted = false,
    refSetter,
    permalinkParam = "aiReport",
    compact = false,
}: Props) {
    const projects = filterByTeam(report.data?.projects ?? [], teamSlug)
    const isMobile = useIsMobile()
    const [copied, setCopied] = useState(false)
    const [linkCopied, setLinkCopied] = useState(false)

    const handleCopy = useCallback(() => {
        navigator.clipboard.writeText(reportToMarkdown(report)).then(() => {
            setCopied(true)
            setTimeout(() => setCopied(false), 1500)
        })
    }, [report])

    const handleCopyLink = useCallback(() => {
        const params = new URLSearchParams(window.location.search)
        params.set(permalinkParam, report.id)
        const url = `${window.location.origin}${window.location.pathname}?${params.toString()}`
        navigator.clipboard.writeText(url).then(() => {
            setLinkCopied(true)
            setTimeout(() => setLinkCopied(false), 1500)
        })
    }, [report.id, permalinkParam])

    return (
        <div
            ref={refSetter}
            className={`gl-panel gl-aircard${highlighted ? " gl-panel--highlight" : ""}`}
            data-report-id={report.id}
        >
            <div className="gl-aircard-head">
                <h3 className="gl-panel-title">{formatDate(report.createdAt)}</h3>
                {!compact && (
                    <div className="gl-aircard-actions">
                        <button
                            className="gl-export-btn"
                            onClick={handleCopyLink}
                            aria-label={`Copy permalink to report from ${formatDate(report.createdAt)}`}
                        >
                            {linkCopied ? "✓ Linked" : "🔗 Link"}
                        </button>
                        <button className="gl-export-btn" onClick={handleCopy}>
                            {copied ? "Copied!" : "Copy"}
                        </button>
                        <button className="gl-export-btn" onClick={() => downloadMarkdown(report)}>
                            Download MD
                        </button>
                    </div>
                )}
            </div>

            {projects.length === 0 ? (
                <p className="gl-empty-text">
                    {teamSlug
                        ? `No project in this report was attributed to ${teamSlug}.`
                        : "No project data in this report."}
                </p>
            ) : (
                <div className="gl-aircard-projects">
                    {projects.map((p, i) => (
                        <ProjectRow key={`${p.project_name}-${i}`} project={p} isMobile={isMobile} />
                    ))}
                </div>
            )}
        </div>
    )
}
