/**
 * Bundle the BARRICADE verify worker into a single self-contained CJS file that
 * the Go backend go:embed's and runs under `node`. esbuild resolves the frontend
 * sim (TypeScript) it imports and inlines it — so the attester runs byte-for-byte
 * the same simulation the client did, with no separate build step at Go compile
 * time and no node_modules in the runtime image.
 *
 * esbuild is resolved from the frontend workspace (the only place it's installed),
 * so this runs from anywhere: `node backend/internal/arcade/worker/build.mjs`.
 *
 * The output (bundle/verify-worker.cjs) is COMMITTED (the dir is `bundle/`, not
 * `dist/`, so the repo-wide dist/ gitignore doesn't swallow it). CI rebuilds it
 * and fails on any diff (see .github/workflows/ci.yml) — a stale bundle can never
 * ship a sim that disagrees with the frontend's.
 */
import { createRequire } from "node:module"
import { fileURLToPath } from "node:url"
import path from "node:path"

const here = path.dirname(fileURLToPath(import.meta.url))
const frontendReq = createRequire(path.join(here, "../../../../frontend/package.json"))
const esbuild = frontendReq("esbuild")

await esbuild.build({
    entryPoints: [path.join(here, "verify_worker.ts")],
    outfile: path.join(here, "bundle/verify-worker.cjs"),
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node18",
    // Determinism/audit: no minification (the bundle is read in review), a banner
    // marking it generated, and a stable footer-free output.
    minify: false,
    legalComments: "none",
    banner: {
        js: "// GENERATED by backend/internal/arcade/worker/build.mjs — DO NOT EDIT.\n// Rebuild: node backend/internal/arcade/worker/build.mjs",
    },
})

console.log("verify-worker.cjs rebuilt")
