import { test, expect } from '@playwright/test'
import { stubNetwork } from './helpers/stubNetwork'

test('System follows device changes; an explicit choice survives reload', async ({ page }) => {
    await stubNetwork(page)
    await page.emulateMedia({ colorScheme: 'light' })
    await page.goto('/pearl/settings')
    await page.getByRole('button', { name: /Appearance/ }).click()
    const theme = page.getByRole('combobox', { name: 'Theme', exact: true })
    await expect(theme).toHaveValue('system')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
    await expect(page.getByRole('button', { name: 'Switch to Black theme' })).toBeVisible()
    await page.emulateMedia({ colorScheme: 'dark' })
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    const shortcut = page.getByRole('button', { name: 'Switch to Light theme' })
    await shortcut.focus()
    await shortcut.press('Enter')
    await expect(theme).toHaveValue('light')
    await page.reload()
    await page.getByRole('button', { name: /Appearance/ }).click()
    await expect(theme).toHaveValue('light')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
    await theme.selectOption('system')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await page.emulateMedia({ colorScheme: 'light' })
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
    await theme.selectOption('dark')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await expect(theme.locator('option:checked')).toHaveText('Black')
})
