import { bech32Encode } from '../src/lib/dao/realmAddress'
import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { stubNetwork } from './helpers/stubNetwork'
import { suppressReleaseAnnouncement } from './helpers/releaseAnnouncement'
import { MAINNET, MEMBER, TEST13, memberWallet, routeV12, v12 } from './helpers/weightedV12Fixture'
import { qevalWire, weightedFixture, weightedRealm } from '../src/lib/dao/testdata/weighted'

for (const version of [1, 2] as const) for (const width of [1280, 390]) {
    test(`weighted DAO v${version} reads remain clear at ${width}px`, async ({ page }, info) => {
        await stubNetwork(page)
        const fixture = weightedFixture(version)
        if (version === 2) fixture.proposal.action = { type: 'recover-member', personId: fixture.members[1].personId, oldAddress: fixture.members[1].address, newAddress: bech32Encode('g', new Uint8Array(20).fill(9)) }
        await page.route('**/status', route => route.fulfill({ json: { result: { node_info: { network: 'gnoland-1' } } } }))
        await page.route('**/abci_query?**', route => {
            const expression = Buffer.from(new URL(route.request().url()).searchParams.get('data')!.slice(2), 'hex').toString('utf8')
            const value = expression.includes('GetConfigJSON') ? fixture.config : expression.includes('GetMembersJSON') ? fixture.roster : fixture.page
            return route.fulfill({ json: { result: { response: { ResponseBase: { Data: Buffer.from(qevalWire(value)).toString('base64'), Error: null } } } } })
        })
        await page.setViewportSize({ width, height: 1100 })
        await suppressReleaseAnnouncement(page)
        await page.addInitScript(() => localStorage.setItem('memba_network', 'mainnet'))
        await page.goto(`/mainnet/weighted-dao/${weightedRealm}`)
        const workspace = page.locator('.weighted-dao')
        await expect(workspace.getByText('Founder · 2 points')).toBeVisible()
        await expect(workspace.getByText('Core developer · 1 point')).toHaveCount(6)
        await expect(workspace.getByText(`${version === 1 ? 'Target' : 'Old address'}: ${fixture.members[1].address}`)).toBeVisible()
        await expect(workspace.getByRole('button', { name: 'Review key recovery proposal' })).toHaveCount(version === 2 ? 1 : 0)
        await expect(workspace.getByRole('button', { name: 'Execute proposal' })).toBeDisabled()
        await expect(workspace.getByRole('button', { name: 'Vote yes' })).toBeDisabled()
        await expect(workspace.getByText('6 points and at least 4 people, then 24 hours')).toBeVisible()
        await expect(workspace.getByText('5 developers, then 72 hours')).toBeVisible()
        expect(await workspace.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
        expect((await new AxeBuilder({ page }).include('.weighted-dao').analyze()).violations).toEqual([])
        // Auth/wallet initialization can remount the scoped workspace while
        // axe runs. Capture only after that replacement read has settled.
        await expect(workspace.getByText('Founder · 2 points')).toBeVisible()
        await expect(workspace.getByText('Reading governance state…')).toHaveCount(0)
        await page.screenshot({ path: info.outputPath(`weighted-dao-v${version}-${width}.png`), fullPage: true, animations: 'disabled' })
    })
}
test('malformed weighted contract never falls back to legacy role controls', async ({ page }) => {
    await stubNetwork(page)
    await page.route('**/status', route => route.fulfill({ json: { result: { node_info: { network: 'gnoland-1' } } } }))
    await page.route('**/abci_query?**', route => route.fulfill({ json: { result: { response: { ResponseBase: { Data: Buffer.from(qevalWire({ schema: 'unknown', kind: 'config' })).toString('base64'), Error: null } } } } }))
    await page.goto(`/mainnet/weighted-dao/${weightedRealm}`)
    await expect(page.locator('.weighted-dao [role=alert]')).toBeVisible()
    await expect(page.locator('.weighted-dao').getByRole('button', { name: 'Review role proposal' })).toHaveCount(0)
})

for (const width of [1280, 390]) {
    test(`weighted DAO v12 adapters, categories and frozen state stay read-only without a member wallet at ${width}px`, async ({ page }, info) => {
        await stubNetwork(page)
        await routeV12(page)
        await page.setViewportSize({ width, height: 1100 })
        await suppressReleaseAnnouncement(page)
        await page.addInitScript(() => localStorage.setItem('memba_network', 'mainnet'))
        await page.goto(`/mainnet/weighted-dao/${weightedRealm}`)
        const workspace = page.locator('.weighted-dao')
        await expect(workspace.getByRole('heading', { name: 'Application adapters' })).toBeVisible()
        await expect(workspace.getByRole('listitem', { name: /adapter$/ })).toHaveCount(10)
        // memba_dao is released from the gnoland-1 hold: what disables the controls is the missing member wallet.
        await expect(workspace.getByText('Mainnet governance is read-only for this DAO in Memba.')).toHaveCount(0)
        await expect(workspace.getByText('Acceptance proposals stay disabled on mainnet until the governance write hold is lifted.')).toHaveCount(0)
        const market = workspace.getByRole('listitem', { name: 'marketPolicy adapter' })
        await expect(market.getByText('Ready to accept')).toBeVisible()
        await expect(market.getByText('Proposing requires a connected, authenticated member on the selected network.')).toBeVisible()
        await expect(market.getByRole('button', { name: 'Propose acceptance' })).toBeDisabled()
        await expect(workspace.getByRole('listitem', { name: 'escrowPolicy adapter' }).getByText('DAO controls')).toBeVisible()
        const fee = workspace.getByRole('article', { name: 'Proposal 17' })
        await expect(fee.getByRole('heading', { name: 'Market config · set-fee' })).toBeVisible()
        await expect(fee.getByText('Financial', { exact: true })).toBeVisible()
        await expect(fee.getByRole('note')).toContainText('invalidates every other outstanding proposal')
        await fee.getByText('State frozen at proposal time').click()
        await expect(fee.getByText('pendingAdmin')).toBeVisible()
        await expect(workspace.getByRole('article', { name: 'Proposal 18' }).getByText('Routine', { exact: true })).toBeVisible()
        for (const button of await workspace.getByRole('button', { name: /^(Vote .*|Execute proposal|Propose acceptance)$/ }).all()) await expect(button).toBeDisabled()
        expect(await workspace.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
        expect((await new AxeBuilder({ page }).include('.weighted-dao').analyze()).violations).toEqual([])
        await expect(workspace.getByText('Reading governance state…')).toHaveCount(0)
        await page.screenshot({ path: info.outputPath(`weighted-dao-v12-${width}.png`), fullPage: true, animations: 'disabled' })
        await workspace.getByRole('button', { name: 'Older proposals' }).click()
        const invalidated = workspace.getByRole('article', { name: 'Proposal 2' })
        await expect(invalidated.getByText(/^Invalidated at block \d+: proposal #4 executed \(gno\.land\/r\/samcrew\/memba_market_config\)\.$/)).toBeVisible()
        await expect(workspace.getByRole('article', { name: 'Proposal 1' }).getByText('EXECUTED')).toBeVisible()
    })
}
test('unknown weighted host versions are refused, not rendered as an older contract', async ({ page }) => {
    await stubNetwork(page)
    await page.route('**/status', route => route.fulfill({ json: { result: { node_info: { network: 'gnoland-1' } } } }))
    await page.route('**/abci_query?**', route => {
        const expression = Buffer.from(new URL(route.request().url()).searchParams.get('data')!.slice(2), 'hex').toString('utf8')
        const bump = (value: unknown) => ({ ...(value as object), schema: 'memba-weighted-host/v13' })
        const value = expression.includes('GetConfigJSON') ? bump(v12.config) : expression.includes('GetMembersJSON') ? bump(v12.members) : bump(v12.proposals_page_1)
        return route.fulfill({ json: { result: { response: { ResponseBase: { Data: Buffer.from(qevalWire(value)).toString('base64'), Error: null } } } } })
    })
    await page.goto(`/mainnet/weighted-dao/${weightedRealm}`)
    await expect(page.locator('.weighted-dao [role=alert]')).toBeVisible()
    await expect(page.locator('.weighted-dao').getByRole('heading', { name: 'Application adapters' })).toHaveCount(0)
    await expect(page.locator('.weighted-dao').getByRole('article')).toHaveCount(0)
})
test('one mis-encoded weighted proposal is listed as unreadable without hiding the rest', async ({ page }) => {
    await stubNetwork(page)
    await routeV12(page)
    const firstPage = structuredClone(v12.proposals_page_1) as { proposals: { action: Record<string, unknown> }[] }
    firstPage.proposals[3].action.operation = 'grant-everything'
    await page.route('**/abci_query?**', async route => {
        const expression = Buffer.from(new URL(route.request().url()).searchParams.get('data')!.slice(2), 'hex').toString('utf8')
        if (!expression.endsWith('GetProposalsJSON(0, 20)')) return route.fallback()
        return route.fulfill({ json: { result: { response: { ResponseBase: { Data: Buffer.from(qevalWire(firstPage)).toString('base64'), Error: null } } } } })
    })
    await page.goto(`/mainnet/weighted-dao/${weightedRealm}`)
    const workspace = page.locator('.weighted-dao')
    await expect(workspace.getByRole('heading', { name: 'Unreadable proposal #23' })).toBeVisible()
    await expect(workspace.getByRole('article')).toHaveCount(20)
    await expect(workspace.getByRole('heading', { name: 'Market config · set-fee' })).toBeVisible()
})

test('weighted DAO v12 on a test network proposes an adapter acceptance with its exact deposit cap', async ({ page }, info) => {
    await stubNetwork(page)
    await routeV12(page, 'test-13')
    await memberWallet(page)
    await suppressReleaseAnnouncement(page)
    await page.goto(`/test13/weighted-dao/${weightedRealm}`)
    const workspace = page.locator('.weighted-dao')
    await expect(workspace.getByText('Mainnet governance is read-only for this DAO in Memba.')).toHaveCount(0)
    const market = workspace.getByRole('listitem', { name: 'marketPolicy adapter' })
    await expect(market.getByText('Ready to accept')).toBeVisible()
    await expect(market.getByText('The proposal locks up to 2.13 GNOT of storage deposit from the proposer.')).toBeVisible()
    // Handoff order: market config is number 1 and, the others being DAO-controlled here, the next one.
    await expect(market.getByText(/^Handoff 1 of 10/)).toBeVisible()
    await expect(workspace.getByText('Next recommended')).toHaveCount(1)
    await expect(market.getByText('Next recommended')).toBeVisible()
    await expect(workspace.getByRole('listitem', { name: /adapter$/ }).last()).toHaveAttribute('aria-label', 'escrowPolicy adapter')
    await expect(workspace.getByText('At least 4 people with 6 points vote yes, then 24 hours pass. Or 5 core developers vote yes, then 72 hours pass.')).toBeVisible()
    await expect(workspace.getByRole('listitem', { name: 'questPolicy adapter' }).getByText('DAO controls')).toBeVisible()
    await expect(workspace.getByRole('listitem', { name: 'questPolicy adapter' }).getByRole('button')).toHaveCount(0)
    // Role and recovery proposals stay unavailable for this contract version.
    await expect(workspace.getByRole('button', { name: 'Review role proposal' })).toBeDisabled()
    const propose = market.getByRole('button', { name: 'Propose acceptance' })
    await expect(propose).toBeEnabled()
    expect((await new AxeBuilder({ page }).include('.weighted-dao').analyze()).violations).toEqual([])
    expect(await workspace.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await market.screenshot({ path: info.outputPath('weighted-dao-v12-acceptance.png'), animations: 'disabled' })
    await propose.click()
    const dialog = page.getByRole('dialog', { name: 'Confirm transaction' })
    await expect(dialog.getByText('ProposeMarketAccept', { exact: true })).toBeVisible()
    await expect(dialog.getByText('Storage deposit cap')).toBeVisible()
    await expect(dialog.getByText('2.13 GNOT', { exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath('weighted-dao-v12-acceptance-confirm.png'), animations: 'disabled' })
    await dialog.getByRole('button', { name: 'Confirm & Broadcast' }).click()
    await expect(workspace.getByText(/^Transaction submitted: (ab){32}\./)).toBeVisible()
    const requests = await page.evaluate(() => (window as unknown as { __signRequests: unknown[] }).__signRequests)
    expect(requests).toHaveLength(1)
    expect(requests[0]).toMatchObject({ gasWanted: 24_000_000, messages: [{ type: '/vm.m_call', value: { caller: MEMBER, send: '', pkg_path: weightedRealm, func: 'ProposeMarketAccept', args: [], max_deposit: '2130000ugnot' } }] })
})
test('weighted DAO v12 on a test network warns before an execution invalidates open proposals', async ({ page }, info) => {
    await stubNetwork(page)
    await routeV12(page, 'test-13')
    await memberWallet(page)
    await suppressReleaseAnnouncement(page)
    await page.goto(`/test13/weighted-dao/${weightedRealm}`)
    const fee = page.locator('.weighted-dao').getByRole('article', { name: 'Proposal 17' })
    await expect(fee.getByRole('button', { name: 'Vote yes' })).toBeEnabled()
    await fee.getByRole('button', { name: 'Execute proposal' }).click()
    const confirm = fee.getByRole('group', { name: 'Confirm execution of proposal 17' })
    await expect(confirm.getByText(/^Executing #17 invalidates \d+ open proposals #\d+(, #\d+)*\./)).toBeVisible()
    await fee.screenshot({ path: info.outputPath('weighted-dao-v12-execute-warning.png'), animations: 'disabled' })
    await confirm.getByRole('button', { name: 'Keep proposals open' }).click()
    await expect(confirm).toHaveCount(0)
    expect(await page.evaluate(() => (window as unknown as { __signRequests: unknown[] }).__signRequests)).toHaveLength(0)
})
/** Every write control is disabled (the same set as on the released DAO) and nothing reached the wallet. */
async function expectEveryControlDisabled(page: Page, workspace: ReturnType<Page['locator']>) {
    const controls = workspace.getByRole('button', { name: /^(Propose acceptance|Vote .*|Execute proposal|Review role proposal)$/ })
    await expect(controls).toHaveCount(CONTROL_COUNT)
    for (const button of await controls.all()) await expect(button).toBeDisabled()
    expect(await page.evaluate(() => (window as unknown as { __signRequests: unknown[] }).__signRequests)).toHaveLength(0)
}
// Write controls the v12 fixture renders for a recognised member, acceptance buttons included.
const CONTROL_COUNT = 82
test('weighted DAO v12 on mainnet lets a member of the released governing DAO propose an acceptance with its exact deposit cap', async ({ page }) => {
    await stubNetwork(page)
    await routeV12(page, 'gnoland-1')
    await memberWallet(page, MAINNET)
    await suppressReleaseAnnouncement(page)
    await page.goto(`/mainnet/weighted-dao/${weightedRealm}`)
    const workspace = page.locator('.weighted-dao')
    const market = workspace.getByRole('listitem', { name: 'marketPolicy adapter' })
    await expect(market.getByText('Ready to accept')).toBeVisible()
    await expect(workspace.getByText('Mainnet governance is read-only for this DAO in Memba.')).toHaveCount(0)
    await expect(workspace.getByRole('article', { name: 'Proposal 17' }).getByRole('button', { name: 'Vote yes' })).toBeEnabled()
    // Role and recovery proposals stay unavailable for this contract version, released or not.
    await expect(workspace.getByRole('button', { name: 'Review role proposal' })).toBeDisabled()
    const propose = market.getByRole('button', { name: 'Propose acceptance' })
    await expect(propose).toBeEnabled()
    await propose.click()
    const dialog = page.getByRole('dialog', { name: 'Confirm transaction' })
    await expect(dialog.getByText('ProposeMarketAccept', { exact: true })).toBeVisible()
    await expect(dialog.getByText('2.13 GNOT', { exact: true })).toBeVisible()
    await dialog.getByRole('button', { name: 'Confirm & Broadcast' }).click()
    await expect(workspace.getByText(/^Transaction submitted: (ab){32}\./)).toBeVisible()
    const requests = await page.evaluate(() => (window as unknown as { __signRequests: unknown[] }).__signRequests)
    expect(requests).toHaveLength(1)
    expect(requests[0]).toMatchObject({ gasWanted: 24_000_000, messages: [{ type: '/vm.m_call', value: { caller: MEMBER, send: '', pkg_path: 'gno.land/r/samcrew/memba_dao', func: 'ProposeMarketAccept', args: [], max_deposit: '2130000ugnot' } }] })
})
test('weighted DAO v12 on mainnet keeps every control of an unreleased DAO disabled for a connected, authenticated member', async ({ page }) => {
    const unreleased = 'gno.land/r/samcrew/memba_dao_v2'
    await stubNetwork(page)
    await routeV12(page, 'gnoland-1', unreleased)
    await memberWallet(page, MAINNET)
    await suppressReleaseAnnouncement(page)
    await page.goto(`/mainnet/weighted-dao/${unreleased}`)
    const workspace = page.locator('.weighted-dao')
    await expect(workspace.getByText('Mainnet governance is read-only for this DAO in Memba.')).toBeVisible()
    await expect(workspace.getByText('Acceptance proposals stay disabled on mainnet until the governance write hold is lifted.')).toBeVisible()
    // The nomination to this DAO is readable, so the acceptance path is on the page, and held.
    const market = workspace.getByRole('listitem', { name: 'marketPolicy adapter' })
    await expect(market.getByText('Ready to accept')).toBeVisible()
    await expect(market.getByRole('button', { name: 'Propose acceptance' })).toBeDisabled()
    // The member is recognised (ballots are read) and still cannot act.
    await expect(workspace.getByRole('article', { name: 'Proposal 17' }).getByText('You have not voted.')).toBeVisible()
    await expectEveryControlDisabled(page, workspace)
    expect(await page.evaluate(() => (window as unknown as { __signRequests: unknown[] }).__signRequests)).toHaveLength(0)
})
test('weighted DAO v12 on mainnet keeps the released governing DAO disabled for a member whose wallet is on another chain', async ({ page }) => {
    await stubNetwork(page)
    await routeV12(page, 'gnoland-1')
    await memberWallet(page, { network: 'mainnet', chainId: TEST13.chainId, rpcUrl: TEST13.rpcUrl })
    await suppressReleaseAnnouncement(page)
    await page.goto(`/mainnet/weighted-dao/${weightedRealm}`)
    const workspace = page.locator('.weighted-dao')
    const market = workspace.getByRole('listitem', { name: 'marketPolicy adapter' })
    await expect(market.getByText('Ready to accept')).toBeVisible()
    await expect(workspace.getByText('Mainnet governance is read-only for this DAO in Memba.')).toHaveCount(0)
    await expect(market.getByRole('button', { name: 'Propose acceptance' })).toBeDisabled()
    await expect(workspace.getByRole('article', { name: 'Proposal 17' }).getByRole('button', { name: 'Vote yes' })).toBeDisabled()
    await expectEveryControlDisabled(page, workspace)
})
