/**
 * Agent Registry Realm Template — generates Gno code for an on-chain agent registry.
 *
 * Phase 4a: Allows DAOs or users to deploy their own agent registry realm
 * where AI agents can self-register with metadata, pricing, and capabilities.
 *
 * Architecture:
 * - Each registry is a standalone realm
 * - Agents register via RegisterAgent() with metadata
 * - Anyone can query via Render() for agent listings
 *
 * Uses centralized sanitizer from templates/sanitizer.ts for Go string escaping.
 * - Reviews are stored on-chain with 1-5 star ratings
 *
 * @module lib/agentTemplate
 */

import { escapeGnoString, validateRealmPath as _validateRealmPath } from "./templates/sanitizer"

// ── Types ────────────────────────────────────────────────────

export interface AgentRegistryConfig {
    /** Realm path (e.g., "gno.land/r/samcrew/agent_registry") */
    realmPath: string
    /** Registry name */
    name: string
    /** Registry description */
    description: string
    /** Admin address (can remove agents) */
    adminAddress: string
}

// ── Code Generation ──────────────────────────────────────────

/** Validate realm path format — delegates to centralized sanitizer. */
function validateRealmPath(path: string): void {
    const err = _validateRealmPath(path)
    if (err) throw new Error(`Invalid realm path: ${err}`)
}

/** Validate Gno address format. */
function validateAddress(addr: string): void {
    if (!/^g1[a-z0-9]{38}$/.test(addr)) {
        throw new Error(`Invalid Gno address: ${addr}`)
    }
}

export function generateAgentRegistryCode(config: AgentRegistryConfig): string {
    validateRealmPath(config.realmPath)
    validateAddress(config.adminAddress)
    const pkgName = config.realmPath.split("/").pop() || "agent_registry"
    const safeName = escapeGnoString(config.name)
    const safeDesc = escapeGnoString(config.description)
    return `package ${pkgName}

// ${config.name} — On-chain AI Agent Registry
// Generated by Memba Agent Marketplace (v3.0)
//
// Render() contract:
//   Home — Render(""):
//     # Registry Name
//     description
//     ## Agents
//     - [AgentName](:agent/id) — short description [category] (rating)
//
//   Agent — Render("agent/id"):
//     # AgentName
//     description
//     **Category:** category
//     **Creator:** g1addr
//     **Endpoint:** endpoint
//     **Transport:** stdio|sse|streamable-http
//     **Pricing:** free|pay-per-use|subscription
//     **Rating:** X.X (N reviews)
//     ## Capabilities
//     - capability1
//     - capability2
//     ## Reviews
//     **g1addr** ★★★★☆ (block H)
//     review text

import (
	"strconv"
	"strings"

	"gno.land/p/nt/avl/v0"
	"gno.land/p/nt/ufmt/v0"

	"chain"
	"chain/banker"
	"chain/runtime"
)

// ── Constants ────────────────────────────────────────────────

const (
	MaxAgents      = 100
	MaxNameLen     = 100
	MaxDescLen     = 1000
	MaxCapsLen     = 2000
	MaxReviewLen   = 500
	AdminAddress   = "${config.adminAddress}"
	RegistryName   = "${safeName}"
	RegistryDesc   = "${safeDesc}"
)

// ── Types ────────────────────────────────────────────────────

type Agent struct {
	ID           string
	Name         string
	Description  string
	Category     string
	Capabilities string // comma-separated
	Creator      address
	Endpoint     string
	Transport    string // "stdio" | "sse" | "streamable-http"
	Pricing      string // "free" | "pay-per-use" | "subscription"
	PricePerCall int64  // in ugnot (0 if free)
	Version      string
	TotalCalls   int64
	RatingSum    int64
	RatingCount  int64
	BlockH       int64
}

type Review struct {
	Reviewer address
	Rating   int  // 1-5
	Comment  string
	BlockH   int64
}

// ── State ────────────────────────────────────────────────────

var (
	agents  *avl.Tree // id -> *Agent
	reviews *avl.Tree // "agentId" -> []*Review
	credits *avl.Tree // "agentId/userAddr" -> int64 (prepaid credits in ugnot)
	usage   *avl.Tree // "agentId/userAddr" -> int64 (total calls)
	idCount int
)

func init() {
	agents = avl.NewTree()
	reviews = avl.NewTree()
	credits = avl.NewTree()
	usage = avl.NewTree()
}

// ── Public Functions ─────────────────────────────────────────

// RegisterAgent registers a new agent in the registry.
func RegisterAgent(
	cur realm,
	id, name, description, category, capabilities,
	endpoint, transport, pricing, version string,
	pricePerCall int64,
) {
	caller := runtime.PreviousRealm().Address()

	if _, exists := agents.Get(id); exists {
		panic("agent ID already exists: " + id)
	}
	if len(id) == 0 || len(id) > 50 {
		panic("ID must be 1-50 characters")
	}
	if len(name) == 0 || len(name) > MaxNameLen {
		panic(ufmt.Sprintf("name must be 1-%d characters", MaxNameLen))
	}
	if len(description) > MaxDescLen {
		panic("description too long")
	}
	if agents.Size() >= MaxAgents {
		panic("registry full")
	}

	a := &Agent{
		ID:           id,
		Name:         name,
		Description:  description,
		Category:     category,
		Capabilities: capabilities,
		Creator:      caller,
		Endpoint:     endpoint,
		Transport:    transport,
		Pricing:      pricing,
		PricePerCall: pricePerCall,
		Version:      version,
		BlockH:       runtime.ChainHeight(),
	}
	agents.Set(id, a)
	reviews.Set(id, []*Review{})
	idCount++
}

// UpdateAgent allows the creator to update their agent.
func UpdateAgent(
	cur realm,
	id, description, capabilities, endpoint, version string,
	pricePerCall int64,
) {
	caller := runtime.PreviousRealm().Address()
	val, exists := agents.Get(id)
	if !exists {
		panic("agent not found: " + id)
	}
	a := val.(*Agent)
	if a.Creator != caller {
		panic("only the creator can update")
	}
	if len(description) > 0 {
		a.Description = description
	}
	if len(capabilities) > 0 {
		a.Capabilities = capabilities
	}
	if len(endpoint) > 0 {
		a.Endpoint = endpoint
	}
	if len(version) > 0 {
		a.Version = version
	}
	a.PricePerCall = pricePerCall
	agents.Set(id, a)
}

// ReviewAgent adds a review for an agent.
func ReviewAgent(cur realm, agentId string, rating int, comment string) {
	caller := runtime.PreviousRealm().Address()

	val, exists := agents.Get(agentId)
	if !exists {
		panic("agent not found")
	}
	if rating < 1 || rating > 5 {
		panic("rating must be 1-5")
	}
	if len(comment) > MaxReviewLen {
		panic("review too long")
	}

	a := val.(*Agent)
	a.RatingSum += int64(rating)
	a.RatingCount++
	agents.Set(agentId, a)

	rval, _ := reviews.Get(agentId)
	revs := rval.([]*Review)
	revs = append(revs, &Review{
		Reviewer: caller,
		Rating:   rating,
		Comment:  comment,
		BlockH:   runtime.ChainHeight(),
	})
	reviews.Set(agentId, revs)
}

// RemoveAgent removes an agent (admin or creator only).
func RemoveAgent(cur realm, id string) {
	caller := runtime.PreviousRealm().Address()
	val, exists := agents.Get(id)
	if !exists {
		panic("agent not found")
	}
	a := val.(*Agent)
	if string(a.Creator) != string(caller) && string(caller) != AdminAddress {
		panic("only creator or admin can remove")
	}
	agents.Remove(id)
	reviews.Remove(id)
}

// ── Pay-Per-Use Credit System ────────────────────────────────

// DepositCredits deposits GNOT as prepaid credits for an agent.
// Send ugnot with the transaction to fund the credits.
func DepositCredits(cur realm, agentId string) {
	caller := runtime.PreviousRealm().Address()
	if _, exists := agents.Get(agentId); !exists {
		panic("agent not found")
	}

	sent := banker.OriginSend()
	if len(sent) == 0 || sent.AmountOf("ugnot") == 0 {
		panic("must send ugnot to deposit credits")
	}
	amount := sent.AmountOf("ugnot")

	key := agentId + "/" + string(caller)
	existing := int64(0)
	if val, ok := credits.Get(key); ok {
		existing = val.(int64)
	}
	credits.Set(key, existing+amount)
}

// UseCredit deducts one invocation credit. Only the agent creator can call this.
// Returns the remaining credits.
func UseCredit(cur realm, agentId, userAddr string) int64 {
	caller := runtime.PreviousRealm().Address()
	val, exists := agents.Get(agentId)
	if !exists {
		panic("agent not found")
	}
	a := val.(*Agent)

	// v3 ACL: only the agent creator (or admin) can consume credits
	if caller != a.Creator && string(caller) != AdminAddress {
		panic("unauthorized: only agent creator or admin can use credits")
	}

	key := agentId + "/" + userAddr
	if a.Pricing == "pay-per-use" && a.PricePerCall > 0 {
		cval, cexists := credits.Get(key)
		if !cexists {
			panic("no credits deposited")
		}
		balance := cval.(int64)
		if balance < a.PricePerCall {
			panic(ufmt.Sprintf("insufficient credits: %d < %d", balance, a.PricePerCall))
		}
		credits.Set(key, balance-a.PricePerCall)
	}

	// Track usage
	a.TotalCalls++
	agents.Set(agentId, a)

	uval := int64(0)
	if uv, uok := usage.Get(key); uok {
		uval = uv.(int64)
	}
	usage.Set(key, uval+1)

	remaining := int64(0)
	if rv, rok := credits.Get(key); rok {
		remaining = rv.(int64)
	}
	return remaining
}

// GetCredits returns the credit balance for a user on an agent.
func GetCredits(agentId, userAddr string) int64 {
	key := agentId + "/" + userAddr
	if val, ok := credits.Get(key); ok {
		return val.(int64)
	}
	return 0
}

// GetUsage returns the total invocation count for a user on an agent.
func GetUsage(agentId, userAddr string) int64 {
	key := agentId + "/" + userAddr
	if val, ok := usage.Get(key); ok {
		return val.(int64)
	}
	return 0
}

// RefundCredits refunds remaining credits to the user.
// Auto-refund: callable by user or admin after 30 days (not enforced in v1).
func RefundCredits(cur realm, agentId string) {
	caller := runtime.PreviousRealm().Address()
	key := agentId + "/" + string(caller)

	cval, cexists := credits.Get(key)
	if !cexists {
		panic("no credits to refund")
	}
	balance := cval.(int64)
	if balance == 0 {
		panic("zero balance")
	}

	// CEI: Effects before Interactions — zero balance BEFORE sending coins
	credits.Set(key, int64(0))

	// Transfer credits back via banker
	bnk := banker.NewBanker(banker.BankerTypeRealmSend)
	bnk.SendCoins(runtime.CurrentRealm().Address(), caller, chain.Coins{chain.NewCoin("ugnot", balance)})
}

// ── Render ───────────────────────────────────────────────────

func Render(path string) string {
	if path == "" {
		return renderHome()
	}
	if strings.HasPrefix(path, "agent/") {
		agentId := strings.TrimPrefix(path, "agent/")
		return renderAgent(agentId)
	}
	return "# 404\\nNot found: " + path
}

func renderHome() string {
	var sb strings.Builder
	sb.WriteString("# " + RegistryName + "\\n\\n")
	sb.WriteString(RegistryDesc + "\\n\\n")
	sb.WriteString("## Agents\\n\\n")

	if agents.Size() == 0 {
		sb.WriteString("*No agents registered yet.*\\n")
		return sb.String()
	}

	agents.Iterate("", "", func(key string, value interface{}) bool {
		a := value.(*Agent)
		rating := "unrated"
		if a.RatingCount > 0 {
			avg := float64(a.RatingSum) / float64(a.RatingCount)
			rating = ufmt.Sprintf("%.1f", avg)
		}
		sb.WriteString(ufmt.Sprintf("- [%s](:agent/%s) — %s [%s] (%s)\\n",
			a.Name, a.ID, truncStr(a.Description, 80), a.Category, rating))
		return false
	})

	return sb.String()
}

func renderAgent(id string) string {
	val, exists := agents.Get(id)
	if !exists {
		return "# 404\\nAgent not found: " + id
	}
	a := val.(*Agent)

	var sb strings.Builder
	sb.WriteString("# " + a.Name + "\\n\\n")
	sb.WriteString(a.Description + "\\n\\n")
	sb.WriteString("**Category:** " + a.Category + "\\n")
	sb.WriteString("**Creator:** " + string(a.Creator) + "\\n")
	sb.WriteString("**Endpoint:** " + a.Endpoint + "\\n")
	sb.WriteString("**Transport:** " + a.Transport + "\\n")
	sb.WriteString("**Pricing:** " + a.Pricing + "\\n")
	if a.PricePerCall > 0 {
		sb.WriteString("**Price:** " + strconv.FormatInt(a.PricePerCall, 10) + " ugnot/call\\n")
	}
	sb.WriteString("**Version:** " + a.Version + "\\n")

	if a.RatingCount > 0 {
		avg := float64(a.RatingSum) / float64(a.RatingCount)
		sb.WriteString(ufmt.Sprintf("**Rating:** %.1f (%d reviews)\\n", avg, a.RatingCount))
	}

	sb.WriteString("\\n## Capabilities\\n\\n")
	for _, cap := range strings.Split(a.Capabilities, ",") {
		cap = strings.TrimSpace(cap)
		if len(cap) > 0 {
			sb.WriteString("- " + cap + "\\n")
		}
	}

	// Reviews
	rval, rexists := reviews.Get(id)
	if rexists {
		revs := rval.([]*Review)
		if len(revs) > 0 {
			sb.WriteString("\\n## Reviews\\n\\n")
			for _, r := range revs {
				stars := strings.Repeat("★", r.Rating) + strings.Repeat("☆", 5-r.Rating)
				sb.WriteString(ufmt.Sprintf("**%s** %s (block %d)\\n\\n",
					truncAddr(r.Reviewer), stars, r.BlockH))
				sb.WriteString(r.Comment + "\\n\\n---\\n\\n")
			}
		}
	}

	return sb.String()
}

// ── Helpers ──────────────────────────────────────────────────

func truncStr(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max-3] + "..."
}

func truncAddr(addr address) string {
	s := string(addr)
	if len(s) > 13 {
		return s[:10] + "..."
	}
	return s
}
`
}

// ── MsgCall Builders ─────────────────────────────────────────

export function buildRegisterAgentMsg(
    callerAddress: string,
    registryPath: string,
    id: string,
    name: string,
    description: string,
    category: string,
    capabilities: string,
    endpoint: string,
    transport: string,
    pricing: string,
    version: string,
    pricePerCall: number,
) {
    return {
        type: "/vm.m_call",
        value: {
            caller: callerAddress,
            send: "",
            pkg_path: registryPath,
            func: "RegisterAgent",
            args: [id, name, description, category, capabilities, endpoint, transport, pricing, version, String(pricePerCall)],
        },
    }
}

export function buildReviewAgentMsg(
    callerAddress: string,
    registryPath: string,
    agentId: string,
    rating: number,
    comment: string,
) {
    return {
        type: "/vm.m_call",
        value: {
            caller: callerAddress,
            send: "",
            pkg_path: registryPath,
            func: "ReviewAgent",
            args: [agentId, String(rating), comment],
        },
    }
}

export function buildUpdateAgentMsg(
    callerAddress: string,
    registryPath: string,
    agentId: string,
    description: string,
    capabilities: string,
    endpoint: string,
    version: string,
    pricePerCall: number,
) {
    return {
        type: "/vm.m_call",
        value: {
            caller: callerAddress,
            send: "",
            pkg_path: registryPath,
            func: "UpdateAgent",
            args: [agentId, description, capabilities, endpoint, version, String(pricePerCall)],
        },
    }
}

export function buildDepositCreditsMsg(
    callerAddress: string,
    registryPath: string,
    agentId: string,
    amountUgnot: number,
) {
    return {
        type: "/vm.m_call",
        value: {
            caller: callerAddress,
            send: `${amountUgnot}ugnot`,
            pkg_path: registryPath,
            func: "DepositCredits",
            args: [agentId],
        },
    }
}

export function buildRefundCreditsMsg(
    callerAddress: string,
    registryPath: string,
    agentId: string,
) {
    return {
        type: "/vm.m_call",
        value: {
            caller: callerAddress,
            send: "",
            pkg_path: registryPath,
            func: "RefundCredits",
            args: [agentId],
        },
    }
}

export function buildDeployAgentRegistryMsg(
    callerAddress: string,
    realmPath: string,
    code: string,
) {
    const pkgName = realmPath.split("/").pop() || "agent_registry"
    return {
        type: "/vm.m_addpkg",
        value: {
            creator: callerAddress,
            package: {
                name: pkgName,
                path: realmPath,
                files: [{ name: `${pkgName}.gno`, body: code }],
            },
            deposit: "",
        },
    }
}
