/**
 * Escrow Realm Template — generates Gno code for milestone-based escrow.
 *
 * Phase 4c: Freelance/Services marketplace escrow system.
 * Inspired by Teritori's projects_manager but rebuilt Memba-native with:
 * - Milestone-based funding (partial payments per deliverable)
 * - Auto-refund timeout (30 days default)
 * - DAO-governed arbitration for disputes
 * - Cancellation fees (configurable %)
 * - Appeal mechanism
 *
 * @module lib/escrowTemplate
 */

import { buildDeployMsg } from "./templates/prologue"

// ── Types ────────────────────────────────────────────────────

export interface EscrowConfig {
    /** Realm path */
    realmPath: string
    /** Admin/arbitrator address */
    adminAddress: string
    /** Platform fee percentage (0-5) */
    platformFeePercent: number
    /** Cancellation fee percentage (0-10) */
    cancellationFeePercent: number
    /** Auto-refund timeout in blocks (~30 days at 3s/block = 864000) */
    autoRefundBlocks: number
    /** Fee recipient address */
    feeRecipient: string
    /**
     * Auto-resolve dispute timeout in blocks.
     * After this many blocks without buyer/seller action, funds auto-release to seller.
     * Default: 0 (disabled). Recommended: 201600 (~7 days at 3s/block).
     */
    autoResolveBlocks?: number
}

export interface ServiceListing {
    id: string
    title: string
    description: string
    category: string
    price: number
    deliveryBlocks: number
    seller: string
    sellerName?: string
    rating: number
    ratingCount: number
    completedJobs: number
    tags: string[]
}

export type ServiceCategory =
    | "development"
    | "design"
    | "writing"
    | "consulting"
    | "marketing"
    | "other"

export const SERVICE_CATEGORIES: { key: ServiceCategory; label: string; icon: string }[] = [
    { key: "development", label: "Development", icon: "💻" },
    { key: "design", label: "Design", icon: "🎨" },
    { key: "writing", label: "Writing", icon: "✍️" },
    { key: "consulting", label: "Consulting", icon: "🧠" },
    { key: "marketing", label: "Marketing", icon: "📣" },
    { key: "other", label: "Other", icon: "🔧" },
]

// ── Seed Listings ────────────────────────────────────────────

export const SEED_LISTINGS: ServiceListing[] = [
    {
        id: "gno-realm-dev",
        title: "Custom Gno Realm Development",
        description: "Build a custom Gno smart contract realm for your project. Includes testing, deployment, and documentation.",
        category: "development",
        price: 5000000,
        deliveryBlocks: 201600,
        seller: "g1example1",
        sellerName: "GnoBuilder",
        rating: 4.8,
        ratingCount: 12,
        completedJobs: 15,
        tags: ["gno", "smart-contract", "realm", "custom"],
    },
    {
        id: "dao-setup",
        title: "DAO Setup & Configuration",
        description: "Set up a complete DAO with governance, treasury, channels, and member management on Memba.",
        category: "consulting",
        price: 2000000,
        deliveryBlocks: 100800,
        seller: "g1example2",
        sellerName: "DAOExpert",
        rating: 4.5,
        ratingCount: 8,
        completedJobs: 10,
        tags: ["dao", "governance", "setup", "consulting"],
    },
    {
        id: "security-audit",
        title: "Gno Realm Security Audit",
        description: "Comprehensive security review of your Gno realm code. Includes vulnerability report and remediation guidance.",
        category: "consulting",
        price: 3000000,
        deliveryBlocks: 201600,
        seller: "g1example3",
        sellerName: "SecureGno",
        rating: 5.0,
        ratingCount: 5,
        completedJobs: 7,
        tags: ["security", "audit", "review", "vulnerabilities"],
    },
]

// ── Query Helpers ────────────────────────────────────────────

export function getListings(category?: ServiceCategory): ServiceListing[] {
    if (category) return SEED_LISTINGS.filter(l => l.category === category)
    return [...SEED_LISTINGS]
}

export function getListing(id: string): ServiceListing | undefined {
    return SEED_LISTINGS.find(l => l.id === id)
}

export function searchListings(query: string, category?: ServiceCategory): ServiceListing[] {
    let results = getListings(category)
    if (query) {
        const q = query.toLowerCase()
        results = results.filter(l =>
            l.title.toLowerCase().includes(q) ||
            l.description.toLowerCase().includes(q) ||
            l.tags.some(t => t.includes(q)),
        )
    }
    return results
}

// ── Escrow Code Generation ───────────────────────────────────

export function generateEscrowCode(config: EscrowConfig): string {
    const pkgName = config.realmPath.split("/").pop() || "escrow"

    return `package ${pkgName}

// Milestone-based Escrow — Generated by Memba Freelance Marketplace (v3.0)
//
// Flow: CreateContract → FundMilestone → CompleteMilestone → ReleaseFunds
// Disputes: RaiseDispute → admin resolves → funds distributed
// Auto-refund: after ${config.autoRefundBlocks} blocks if milestone not completed

import (
	"strconv"
	"strings"

	"gno.land/p/demo/avl"
	"gno.land/p/demo/ufmt"

	"chain"
	"chain/banker"
	"chain/runtime"
)

const (
	AdminAddress       = "${config.adminAddress}"
	PlatformFee        = ${config.platformFeePercent}
	CancellationFee    = ${config.cancellationFeePercent}
	AutoRefundBlocks   = int64(${config.autoRefundBlocks})
	FeeRecipient       = "${config.feeRecipient}"
)

type ContractStatus string
const (
	StatusActive    ContractStatus = "active"
	StatusCompleted ContractStatus = "completed"
	StatusDisputed  ContractStatus = "disputed"
	StatusCancelled ContractStatus = "cancelled"
	StatusRefunded  ContractStatus = "refunded"
)

type MilestoneStatus string
const (
	MsPending   MilestoneStatus = "pending"
	MsFunded    MilestoneStatus = "funded"
	MsCompleted MilestoneStatus = "completed"
	MsReleased  MilestoneStatus = "released"
	MsDisputed  MilestoneStatus = "disputed"
)

type Contract struct {
	ID          string
	Client      address
	Freelancer  address
	Title       string
	Description string
	Status      ContractStatus
	CreatedAt   int64
	Milestones  []Milestone
}

type Milestone struct {
	ID          int
	Title       string
	Amount      int64
	Status      MilestoneStatus
	FundedAt    int64
	CompletedAt int64
}

var (
	contracts *avl.Tree
	nextID    int
)

func init() {
	contracts = avl.NewTree()
}

// CreateContract creates a new escrow contract with milestones.
func CreateContract(cur realm, freelancer address, title, description string, milestones string) string {
	caller := runtime.PreviousRealm().Address()
	id := strconv.Itoa(nextID)
	nextID++

	// Parse milestones: "title1:amount1,title2:amount2"
	ms := parseMilestones(milestones)
	if len(ms) == 0 {
		panic("at least one milestone required")
	}

	c := &Contract{
		ID:          id,
		Client:      caller,
		Freelancer:  freelancer,
		Title:       title,
		Description: description,
		Status:      StatusActive,
		CreatedAt:   runtime.ChainHeight(),
		Milestones:  ms,
	}
	contracts.Set(id, c)
	return id
}

// FundMilestone deposits funds for a specific milestone.
func FundMilestone(cur realm, contractId string, milestoneIdx int) {
	caller := runtime.PreviousRealm().Address()
	c := getContract(contractId)

	if c.Client != caller {
		panic("only client can fund")
	}
	if c.Status != StatusActive {
		panic("contract not active")
	}
	if milestoneIdx < 0 || milestoneIdx >= len(c.Milestones) {
		panic("invalid milestone index")
	}

	ms := &c.Milestones[milestoneIdx]
	if ms.Status != MsPending {
		panic("milestone already funded")
	}

	sent := banker.OriginSend()
	if sent.AmountOf("ugnot") < ms.Amount {
		panic(ufmt.Sprintf("insufficient funds: need %d ugnot", ms.Amount))
	}

	ms.Status = MsFunded
	ms.FundedAt = runtime.ChainHeight()
	contracts.Set(contractId, c)
}

// CompleteMilestone marks a milestone as completed by the freelancer.
func CompleteMilestone(cur realm, contractId string, milestoneIdx int) {
	caller := runtime.PreviousRealm().Address()
	c := getContract(contractId)

	if milestoneIdx < 0 || milestoneIdx >= len(c.Milestones) {
		panic("invalid milestone index")
	}
	if c.Freelancer != caller {
		panic("only freelancer can mark complete")
	}
	ms := &c.Milestones[milestoneIdx]
	if ms.Status != MsFunded {
		panic("milestone not funded")
	}

	ms.Status = MsCompleted
	ms.CompletedAt = runtime.ChainHeight()
	contracts.Set(contractId, c)
}

// ReleaseFunds releases funds to freelancer after client approves completion.
func ReleaseFunds(cur realm, contractId string, milestoneIdx int) {
	caller := runtime.PreviousRealm().Address()
	c := getContract(contractId)

	if c.Client != caller && string(caller) != AdminAddress {
		panic("only client or admin can release")
	}
	if milestoneIdx < 0 || milestoneIdx >= len(c.Milestones) {
		panic("invalid milestone index")
	}
	ms := &c.Milestones[milestoneIdx]
	if ms.Status != MsCompleted {
		panic("milestone not completed")
	}

	// Calculate fees
	platformAmount := (ms.Amount * int64(PlatformFee)) / 100
	freelancerAmount := ms.Amount - platformAmount

	// STATE-BEFORE-SEND INVARIANT: Update state BEFORE external calls.
	// This prevents reentrancy attacks where a malicious contract could
	// re-enter during SendCoins and exploit a stale state (e.g., double-release).
	// Always: (1) update milestone status, (2) persist to storage, (3) THEN send coins.
	ms.Status = MsReleased

	// Check if all milestones released
	allReleased := true
	for _, m := range c.Milestones {
		if m.Status != MsReleased {
			allReleased = false
			break
		}
	}
	if allReleased {
		c.Status = StatusCompleted
	}
	contracts.Set(contractId, c)

	bnk := banker.NewBanker(banker.BankerTypeRealmSend)
	realmAddr := runtime.CurrentRealm().Address()

	// Pay freelancer
	bnk.SendCoins(realmAddr, c.Freelancer, chain.Coins{chain.NewCoin("ugnot", freelancerAmount)})
	// Pay platform fee
	if platformAmount > 0 {
		bnk.SendCoins(realmAddr, address(FeeRecipient), chain.Coins{chain.NewCoin("ugnot", platformAmount)})
	}
}

// RaiseDispute escalates a milestone to admin arbitration.
func RaiseDispute(cur realm, contractId string, milestoneIdx int) {
	caller := runtime.PreviousRealm().Address()
	c := getContract(contractId)

	if c.Client != caller && c.Freelancer != caller {
		panic("only client or freelancer can dispute")
	}
	if milestoneIdx < 0 || milestoneIdx >= len(c.Milestones) {
		panic("invalid milestone index")
	}

	ms := &c.Milestones[milestoneIdx]
	if ms.Status != MsFunded && ms.Status != MsCompleted {
		panic("can only dispute funded or completed milestones")
	}

	ms.Status = MsDisputed
	c.Status = StatusDisputed
	contracts.Set(contractId, c)
}

// ResolveDispute resolves a dispute (admin only). Refund=true refunds client, false pays freelancer.
func ResolveDispute(cur realm, contractId string, milestoneIdx int, refundClient bool) {
	caller := runtime.PreviousRealm().Address()
	if string(caller) != AdminAddress {
		panic("only admin can resolve disputes")
	}

	c := getContract(contractId)
	if milestoneIdx < 0 || milestoneIdx >= len(c.Milestones) {
		panic("invalid milestone index")
	}
	ms := &c.Milestones[milestoneIdx]
	if ms.Status != MsDisputed {
		panic("milestone not in dispute")
	}

	// STATE-BEFORE-SEND INVARIANT: Update state before external coin transfers.
	// See ReleaseFunds for detailed explanation of this reentrancy guard pattern.
	if refundClient {
		ms.Status = MsPending
	} else {
		ms.Status = MsReleased
	}
	c.Status = StatusActive
	contracts.Set(contractId, c)

	bnk := banker.NewBanker(banker.BankerTypeRealmSend)
	realmAddr := runtime.CurrentRealm().Address()

	if refundClient {
		bnk.SendCoins(realmAddr, c.Client, chain.Coins{chain.NewCoin("ugnot", ms.Amount)})
	} else {
		platformAmount := (ms.Amount * int64(PlatformFee)) / 100
		freelancerAmount := ms.Amount - platformAmount
		bnk.SendCoins(realmAddr, c.Freelancer, chain.Coins{chain.NewCoin("ugnot", freelancerAmount)})
		if platformAmount > 0 {
			bnk.SendCoins(realmAddr, address(FeeRecipient), chain.Coins{chain.NewCoin("ugnot", platformAmount)})
		}
	}
}

// CancelContract cancels with cancellation fee.
func CancelContract(cur realm, contractId string) {
	caller := runtime.PreviousRealm().Address()
	c := getContract(contractId)

	if c.Client != caller {
		panic("only client can cancel")
	}
	if c.Status != StatusActive {
		panic("contract not active")
	}

	// STATE-BEFORE-SEND INVARIANT: Update all milestone states before any transfers.
	// Cancel and persist first, then refund — prevents reentrancy during coin sends.
	for i, ms := range c.Milestones {
		if ms.Status == MsFunded {
			c.Milestones[i].Status = MsPending
		}
	}
	c.Status = StatusCancelled
	contracts.Set(contractId, c)

	bnk := banker.NewBanker(banker.BankerTypeRealmSend)
	realmAddr := runtime.CurrentRealm().Address()

	// Refund funded milestones minus cancellation fee
	for _, ms := range c.Milestones {
		if ms.Status == MsPending && ms.FundedAt > 0 {
			fee := (ms.Amount * int64(CancellationFee)) / 100
			refund := ms.Amount - fee
			if refund > 0 {
				bnk.SendCoins(realmAddr, c.Client, chain.Coins{chain.NewCoin("ugnot", refund)})
			}
			if fee > 0 {
				bnk.SendCoins(realmAddr, c.Freelancer, chain.Coins{chain.NewCoin("ugnot", fee)})
			}
		}
	}
}

// ── Render ───────────────────────────────────────────────────

func Render(path string) string {
	if path == "" {
		return renderHome()
	}
	if strings.HasPrefix(path, "contract/") {
		id := strings.TrimPrefix(path, "contract/")
		return renderContract(id)
	}
	return "# 404\\nNot found: " + path
}

func renderHome() string {
	var sb strings.Builder
	sb.WriteString("# Escrow Contracts\\n\\n")

	if contracts.Size() == 0 {
		sb.WriteString("*No contracts yet.*\\n")
		return sb.String()
	}

	contracts.Iterate("", "", func(key string, value interface{}) bool {
		c := value.(*Contract)
		total := int64(0)
		for _, ms := range c.Milestones {
			total += ms.Amount
		}
		sb.WriteString(ufmt.Sprintf("- [%s](:contract/%s) — %s → %s [%s] (%d ugnot)\\n",
			c.Title, c.ID, truncAddr(c.Client), truncAddr(c.Freelancer), string(c.Status), total))
		return false
	})

	return sb.String()
}

func renderContract(id string) string {
	val, exists := contracts.Get(id)
	if !exists {
		return "# 404\\nContract not found: " + id
	}
	c := val.(*Contract)

	var sb strings.Builder
	sb.WriteString("# " + c.Title + "\\n\\n")
	sb.WriteString(c.Description + "\\n\\n")
	sb.WriteString("**Client:** " + string(c.Client) + "\\n")
	sb.WriteString("**Freelancer:** " + string(c.Freelancer) + "\\n")
	sb.WriteString("**Status:** " + string(c.Status) + "\\n")
	sb.WriteString("**Created:** block " + strconv.FormatInt(c.CreatedAt, 10) + "\\n\\n")

	sb.WriteString("## Milestones\\n\\n")
	for _, ms := range c.Milestones {
		sb.WriteString(ufmt.Sprintf("- **%s** — %d ugnot [%s]\\n", ms.Title, ms.Amount, string(ms.Status)))
	}

	return sb.String()
}

// ── Helpers ──────────────────────────────────────────────────

func getContract(id string) *Contract {
	val, exists := contracts.Get(id)
	if !exists {
		panic("contract not found: " + id)
	}
	return val.(*Contract)
}

func parseMilestones(input string) []Milestone {
	var result []Milestone
	parts := strings.Split(input, ",")
	for i, p := range parts {
		p = strings.TrimSpace(p)
		kv := strings.SplitN(p, ":", 2)
		if len(kv) != 2 {
			continue
		}
		amount, err := strconv.ParseInt(strings.TrimSpace(kv[1]), 10, 64)
		if err != nil || amount <= 0 {
			continue
		}
		result = append(result, Milestone{
			ID:     i,
			Title:  strings.TrimSpace(kv[0]),
			Amount: amount,
			Status: MsPending,
		})
	}
	return result
}

func truncAddr(addr address) string {
	s := string(addr)
	if len(s) > 13 {
		return s[:10] + "..."
	}
	return s
}
`
}

// ── MsgCall Builders ─────────────────────────────────────────

export function buildCreateContractMsg(
    caller: string, escrowPath: string, freelancer: string,
    title: string, description: string, milestones: string,
) {
    return {
        type: "/vm.m_call",
        value: { caller, send: "", pkg_path: escrowPath, func: "CreateContract",
            args: [freelancer, title, description, milestones] },
    }
}

export function buildFundMilestoneMsg(
    caller: string, escrowPath: string, contractId: string,
    milestoneIdx: number, amountUgnot: number,
) {
    return {
        type: "/vm.m_call",
        value: { caller, send: `${amountUgnot}ugnot`, pkg_path: escrowPath,
            func: "FundMilestone", args: [contractId, String(milestoneIdx)] },
    }
}

export function buildCompleteMilestoneMsg(
    caller: string, escrowPath: string, contractId: string, milestoneIdx: number,
) {
    return {
        type: "/vm.m_call",
        value: { caller, send: "", pkg_path: escrowPath,
            func: "CompleteMilestone", args: [contractId, String(milestoneIdx)] },
    }
}

export function buildReleaseFundsMsg(
    caller: string, escrowPath: string, contractId: string, milestoneIdx: number,
) {
    return {
        type: "/vm.m_call",
        value: { caller, send: "", pkg_path: escrowPath,
            func: "ReleaseFunds", args: [contractId, String(milestoneIdx)] },
    }
}

export function buildRaiseDisputeMsg(
    caller: string, escrowPath: string, contractId: string, milestoneIdx: number,
) {
    return {
        type: "/vm.m_call",
        value: { caller, send: "", pkg_path: escrowPath,
            func: "RaiseDispute", args: [contractId, String(milestoneIdx)] },
    }
}

/**
 * Build a MsgAddPackage for deploying an escrow realm.
 * @deprecated Use `buildDeployMsg` from `templates/prologue` directly.
 */
export function buildDeployEscrowMsg(caller: string, realmPath: string, code: string) {
    return buildDeployMsg(caller, realmPath, code)
}
