/**
 * gnoloveExport — CSV, Markdown, and PDF export utilities for the weekly report.
 *
 * jsPDF + jspdf-autotable are loaded dynamically inside exportToPDF so they
 * don't enter the lazy gnolove chunk's first-paint graph (~85 KB gz saved).
 *
 * @module lib/gnoloveExport
 */

import type { TPullRequest } from "./gnoloveSchemas"

export type ReportStatusResolver = (pr: TPullRequest) => string

function reportStatus(pr: TPullRequest, resolve?: ReportStatusResolver): string {
    return resolve?.(pr) ?? (pr.mergedAt || pr.state === "MERGED" ? "Merged" : "Open")
}

/** Prevent CSV formula injection — prefix dangerous first characters with a tab. */
function sanitizeCSVCell(value: string): string {
    if (/^[=+\-@\t\r]/.test(value)) return `\t${value}`
    return value
}

/** Treat API text as plain text in exported Markdown. */
export function escapeMarkdownText(value: string): string {
    return value.replace(/[\\`*_{}[\]()#+.!|<>~-]/g, c => `\\${c}`)
}

export function safeGitHubPrUrl(value: string): string | null {
    try {
        for (const char of value) {
            const code = char.charCodeAt(0)
            if (code <= 0x20 || code === 0x7f) return null
        }
        const url = new URL(value)
        if (url.protocol !== "https:" || url.hostname !== "github.com" || url.port || url.username || url.password) return null
        if (!/^\/[^/]+\/[^/]+\/pull\/\d+\/?$/.test(url.pathname)) return null
        return `${url.origin}${url.pathname}`.replace(/\(/g, "%28").replace(/\)/g, "%29")
    } catch {
        return null
    }
}

export function generateCSV(prs: TPullRequest[], resolveStatus?: ReportStatusResolver): string {
    const headers = ["Title", "Number", "Author", "Report Status", "State", "Review Decision", "Draft", "URL", "Created", "Merged"]
    const rows = prs.map(pr => [
        `"${sanitizeCSVCell(pr.title.replace(/"/g, '""'))}"`,
        pr.number,
        sanitizeCSVCell(pr.authorLogin ?? ""),
        sanitizeCSVCell(reportStatus(pr, resolveStatus)),
        pr.state,
        pr.reviewDecision ?? "",
        pr.isDraft ? "Yes" : "No",
        safeGitHubPrUrl(pr.url) ?? "",
        pr.createdAt,
        pr.mergedAt ?? "",
    ])
    return [headers.join(","), ...rows.map(r => r.join(","))].join("\n")
}

export function generateMarkdown(prs: TPullRequest[], tab: string, dateLabel: string, periodLabel = "Weekly", resolveStatus?: ReportStatusResolver): string {
    const tabLabel = tab.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase())
    const lines = [
        `# Gnolove ${periodLabel} Report — ${escapeMarkdownText(dateLabel)}`,
        `## ${tabLabel}`,
        "",
        `| # | Title | Author | Report Status | State |`,
        `|---|-------|--------|---------------|-------|`,
        ...prs.map(pr => {
            const title = escapeMarkdownText(pr.title)
            const url = safeGitHubPrUrl(pr.url)
            return `| #${pr.number} | ${url ? `[${title}](${url})` : title} | @${escapeMarkdownText(pr.authorLogin ?? "unknown")} | ${escapeMarkdownText(reportStatus(pr, resolveStatus))} | ${escapeMarkdownText(pr.state)} |`
        }),
        "",
        `_Generated by Gnolove on ${new Date().toISOString().split("T")[0]}_`,
    ]
    return lines.join("\n")
}

export function exportToCSV(prs: TPullRequest[], tab: string, weekLabel: string, resolveStatus?: ReportStatusResolver): void {
    downloadFile(generateCSV(prs, resolveStatus), `gnolove-report-${tab}-${weekLabel}.csv`, "text/csv")
}

export function exportToMarkdown(prs: TPullRequest[], tab: string, dateLabel: string, periodLabel = "Weekly", resolveStatus?: ReportStatusResolver): void {
    downloadFile(generateMarkdown(prs, tab, dateLabel, periodLabel, resolveStatus), `gnolove-report-${tab}-${dateLabel}.md`, "text/markdown")
}

export async function exportToPDF(prs: TPullRequest[], tab: string, weekLabel: string, resolveStatus?: ReportStatusResolver): Promise<void> {
    const [{ jsPDF }, { default: autoTable }] = await Promise.all([
        import("jspdf"),
        import("jspdf-autotable"),
    ])

    const tabLabel = tab.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase())
    const doc = new jsPDF()
    doc.setFontSize(14)
    doc.text(`Gnolove PR Report - ${weekLabel}`, 14, 15)
    doc.setFontSize(10)
    doc.text(`Status: ${tabLabel} | ${prs.length} PRs`, 14, 22)

    autoTable(doc, {
        startY: 28,
        head: [["#", "Title", "Author", "Report Status", "State"]],
        body: prs.map(pr => [
            `#${pr.number}`,
            pr.title.length > 60 ? pr.title.slice(0, 57) + "..." : pr.title,
            pr.authorLogin ?? "unknown",
            reportStatus(pr, resolveStatus),
            pr.state,
        ]),
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [30, 30, 50] },
    })

    doc.save(`gnolove-report-${tab}-${weekLabel}.pdf`)
}

function downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
}
