/**
 * Tests for gnoloveExport.ts — CSV and Markdown generation.
 *
 * @module lib/gnoloveExport.test
 */

import { describe, it, expect } from "vitest"
import { generateCSV, generateMarkdown } from "./gnoloveExport"
import type { TPullRequest } from "./gnoloveSchemas"

const samplePR = {
    id: "1",
    number: 42,
    state: "MERGED",
    title: "Fix bug in auth flow",
    url: "https://github.com/gnolang/gno/pull/42",
    authorLogin: "alice",
    authorAvatarUrl: "https://example.com/avatar.png",
    mergedAt: "2026-03-20T10:00:00Z",
    isDraft: false,
    reviewDecision: "APPROVED",
    createdAt: "2026-03-18T08:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
} as unknown as TPullRequest

const prWithSpecialChars = {
    ...samplePR,
    id: "2",
    number: 43,
    title: 'Add "feature", with commas',
    authorLogin: "bob",
} as unknown as TPullRequest

describe("generateCSV", () => {
    it("produces valid CSV with headers", () => {
        const csv = generateCSV([samplePR])
        const lines = csv.split("\n")
        expect(lines[0]).toBe("Title,Number,Author,State,Review Decision,Draft,URL,Created,Merged")
        expect(lines).toHaveLength(2)
    })

    it("escapes double quotes in titles", () => {
        const csv = generateCSV([prWithSpecialChars])
        expect(csv).toContain('""feature""')
    })

    it("handles empty PR array", () => {
        const csv = generateCSV([])
        const lines = csv.split("\n")
        expect(lines).toHaveLength(1) // only header
    })

    it("includes all fields", () => {
        const csv = generateCSV([samplePR])
        const row = csv.split("\n")[1]
        expect(row).toContain("42")
        expect(row).toContain("alice")
        expect(row).toContain("MERGED")
        expect(row).toContain("APPROVED")
    })

    it("sanitizes formula injection in titles", () => {
        const malicious = { ...samplePR, id: "99", title: '=HYPERLINK("http://evil.com","Click")' } as unknown as TPullRequest
        const csv = generateCSV([malicious])
        // Should prefix with tab to prevent Excel formula execution
        expect(csv).not.toContain('"=HYPERLINK')
        expect(csv).toContain('\t=HYPERLINK')
    })

    it("sanitizes plus/minus/at prefixed titles", () => {
        const plusPR = { ...samplePR, id: "100", title: "+cmd|'/C calc'!A0" } as unknown as TPullRequest
        const csv = generateCSV([plusPR])
        expect(csv).toContain("\t+cmd")
    })
})

describe("generateMarkdown", () => {
    it("produces valid Markdown table", () => {
        const md = generateMarkdown([samplePR], "merged", "Mar 18 — Mar 24, 2026")
        expect(md).toContain("# Gnolove Weekly Report")
        expect(md).toContain("## Merged")
        expect(md).toContain("| # | Title | Author | State |")
        expect(md).toContain("#42")
        expect(md).toContain("@alice")
    })

    it("escapes pipe characters in titles", () => {
        const prWithPipe = { ...samplePR, id: "3", title: "Fix | character in title" } as unknown as TPullRequest
        const md = generateMarkdown([prWithPipe], "merged", "test-week")
        expect(md).toContain("Fix \\| character in title")
    })

    it("escapes bracket characters to prevent link injection", () => {
        const prWithBrackets = { ...samplePR, id: "4", title: "]click[here](http://evil.com)" } as unknown as TPullRequest
        const md = generateMarkdown([prWithBrackets], "merged", "test-week")
        // Brackets should be escaped to prevent breaking markdown link syntax
        expect(md).toContain("\\]")
        expect(md).toContain("\\[")
    })

    it("formats tab labels correctly", () => {
        const md = generateMarkdown([], "in_progress", "test-week")
        expect(md).toContain("## In Progress")
    })

    it("handles empty PR array", () => {
        const md = generateMarkdown([], "waiting_for_review", "test-week")
        expect(md).toContain("## Waiting For Review")
        expect(md).not.toContain("| #4")
    })

    it("includes generation date", () => {
        const md = generateMarkdown([samplePR], "merged", "test-week")
        const today = new Date().toISOString().split("T")[0]
        expect(md).toContain(`_Generated by Gnolove on ${today}_`)
    })
})
