import type { TAIReport, TAIReportProject } from "./gnoloveSchemas"

/** AI text is shown as plain text in the app, so exports keep it plain too. */
function escapeMarkdownText(value: string): string {
    return value
        .replace(/\r\n?/g, "\n")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/([\\`*_{}[\]()#+\-.!|~=])/g, "\\$1")
}

export function aiReportDate(createdAt: string): string {
    const date = new Date(createdAt)
    return Number.isFinite(date.getTime()) ? date.toISOString().slice(0, 10) : "unknown-date"
}

function displayDate(createdAt: string): string {
    const date = new Date(createdAt)
    return Number.isFinite(date.getTime())
        ? date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
        : "Unknown date"
}

function longestText(project: TAIReportProject): string {
    return project.summary_long || project.summary || project.summary_short || ""
}

export function reportToMarkdown(report: TAIReport): string {
    const date = aiReportDate(report.createdAt)
    const projects = report.data?.projects ?? []
    return [
        `# Weekly Ecosystem Report — ${displayDate(report.createdAt)}`,
        "",
        ...projects.flatMap(project => [
            `## ${escapeMarkdownText(project.project_name)}`,
            "",
            escapeMarkdownText(longestText(project)),
            "",
        ]),
        `_Generated by gnolove AI on ${date}_`,
    ].join("\n")
}
