/**
 * gnoloveExport — CSV and Markdown export utilities for the weekly report.
 *
 * @module lib/gnoloveExport
 */

import type { TPullRequest } from "./gnoloveSchemas"

/** Prevent CSV formula injection — prefix dangerous first characters with a tab. */
function sanitizeCSVCell(value: string): string {
    if (/^[=+\-@\t\r]/.test(value)) return `\t${value}`
    return value
}

/** Escape characters that break Markdown link/table syntax. */
function sanitizeMDText(value: string): string {
    return value.replace(/[|[\]]/g, c => `\\${c}`)
}

export function generateCSV(prs: TPullRequest[]): string {
    const headers = ["Title", "Number", "Author", "State", "Review Decision", "Draft", "URL", "Created", "Merged"]
    const rows = prs.map(pr => [
        `"${sanitizeCSVCell(pr.title.replace(/"/g, '""'))}"`,
        pr.number,
        sanitizeCSVCell(pr.authorLogin ?? ""),
        pr.state,
        pr.reviewDecision ?? "",
        pr.isDraft ? "Yes" : "No",
        pr.url,
        pr.createdAt,
        pr.mergedAt ?? "",
    ])
    return [headers.join(","), ...rows.map(r => r.join(","))].join("\n")
}

export function generateMarkdown(prs: TPullRequest[], tab: string, weekLabel: string): string {
    const tabLabel = tab.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase())
    const lines = [
        `# Gnolove Weekly Report — ${weekLabel}`,
        `## ${tabLabel}`,
        "",
        `| # | Title | Author | State |`,
        `|---|-------|--------|-------|`,
        ...prs.map(pr =>
            `| #${pr.number} | [${sanitizeMDText(pr.title)}](${pr.url}) | @${sanitizeMDText(pr.authorLogin ?? "unknown")} | ${pr.state} |`
        ),
        "",
        `_Generated by Gnolove on ${new Date().toISOString().split("T")[0]}_`,
    ]
    return lines.join("\n")
}

export function exportToCSV(prs: TPullRequest[], tab: string, weekLabel: string): void {
    downloadFile(generateCSV(prs), `gnolove-report-${tab}-${weekLabel}.csv`, "text/csv")
}

export function exportToMarkdown(prs: TPullRequest[], tab: string, weekLabel: string): void {
    downloadFile(generateMarkdown(prs, tab, weekLabel), `gnolove-report-${tab}-${weekLabel}.md`, "text/markdown")
}

function downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
}
