/**
 * GRC1155 Template — generates self-contained Gno code for multi-token (edition) NFTs.
 *
 * v3.1: Follows nftTemplate.ts pattern but for GRC1155 (ERC-1155 equivalent).
 * Generates a self-contained realm with:
 * - Batch mint/transfer operations
 * - Per-token-ID supply caps
 * - URI-based metadata
 * - Admin/public mint toggle
 * - Render() gallery display
 *
 * @module lib/grc1155Template
 */

// ── Types ────────────────────────────────────────────────────

export interface GRC1155CollectionConfig {
    /** Realm path (e.g., "gno.land/r/user/my_editions") */
    realmPath: string
    /** Collection name */
    name: string
    /** Collection URI (metadata endpoint) */
    uri: string
    /** Collection description */
    description: string
    /** Creator/admin address */
    adminAddress: string
    /** Max supply per token ID (0 = unlimited) */
    maxPerToken: number
    /** Whether anyone can mint or only admin */
    publicMint: boolean
    /** Mint price per unit in ugnot (0 = free) */
    mintPriceUgnot: number
}

/**
 * Generate self-contained GRC1155 realm code.
 * This produces deployable code that doesn't depend on external packages
 * beyond chain/* builtins and avl/ufmt.
 */
export function generateGRC1155Code(config: GRC1155CollectionConfig): string {
    const pkgName = config.realmPath.split("/").pop() || "my_editions"

    return `package ${pkgName}

// ${config.name} — GRC1155 Multi-Token Collection
// Generated by Memba NFT Launchpad v3.1
//
// URI: ${config.uri || "(none)"}
// Admin: ${config.adminAddress}
// Max per token: ${config.maxPerToken || "unlimited"}
// Mint: ${config.publicMint ? "public" : "admin only"}
// Price: ${config.mintPriceUgnot > 0 ? config.mintPriceUgnot + " ugnot" : "free"}

import (
\t"strconv"
\t"strings"

\t"chain/runtime"

\t"gno.land/p/nt/avl/v0"
\t"gno.land/p/nt/ufmt/v0"
)

// ── Constants ────────────────────────────────────────────────

const (
\tName         = "${escapeGnoString(config.name)}"
\tURI          = "${escapeGnoString(config.uri)}"
\tDescription  = "${escapeGnoString(config.description)}"
\tAdminAddress = "${config.adminAddress}"
\tMaxPerToken  = ${config.maxPerToken}  // 0 = unlimited
\tPublicMint   = ${config.publicMint}
\tMintPrice    = int64(${config.mintPriceUgnot}) // ugnot per unit
)

// ── State ────────────────────────────────────────────────────

var (
\tbalances          *avl.Tree // "tokenId:address" -> int64
\toperatorApprovals *avl.Tree // "owner:operator" -> bool
\ttokenSupply       *avl.Tree // "tokenId" -> int64 (total minted)
\ttokenURIs         *avl.Tree // "tokenId" -> string (per-token URI override)
\tnextTokenId       int64
)

func init() {
\tbalances = avl.NewTree()
\toperatorApprovals = avl.NewTree()
\ttokenSupply = avl.NewTree()
\ttokenURIs = avl.NewTree()
}

// ── Mint ─────────────────────────────────────────────────────

// Mint creates \`amount\` units of a new token ID, assigned to \`to\`.
func Mint(cur realm, to address, amount int64) string {
\tcaller := runtime.PreviousRealm().Address()

\t// Access control
\tif !PublicMint && caller != address(AdminAddress) {
\t\tpanic("admin only: minting restricted")
\t}

\tif amount <= 0 {
\t\tpanic("amount must be > 0")
\t}

\tnextTokenId++
\ttid := strconv.FormatInt(nextTokenId, 10)

\t// Check per-token cap
\tif MaxPerToken > 0 && amount > int64(MaxPerToken) {
\t\tpanic(ufmt.Sprintf("exceeds max per token: %d", MaxPerToken))
\t}

\t// Set balance
\tkey := tid + ":" + to.String()
\tbalances.Set(key, amount)

\t// Track supply
\ttokenSupply.Set(tid, amount)

\treturn tid
}

// MintExisting mints additional units of an existing token ID.
func MintExisting(cur realm, tid string, to address, amount int64) {
\tcaller := runtime.PreviousRealm().Address()

\tif !PublicMint && caller != address(AdminAddress) {
\t\tpanic("admin only: minting restricted")
\t}
\tif amount <= 0 {
\t\tpanic("amount must be > 0")
\t}

\t// Check supply cap
\tcurrentSupply := getSupply(tid)
\tif MaxPerToken > 0 && currentSupply+amount > int64(MaxPerToken) {
\t\tpanic(ufmt.Sprintf("exceeds max supply for token %s: %d + %d > %d",
\t\t\ttid, currentSupply, amount, MaxPerToken))
\t}

\t// Update balance
\tkey := tid + ":" + to.String()
\toldBal := getBalance(key)
\tbalances.Set(key, oldBal+amount)

\t// Update supply
\ttokenSupply.Set(tid, currentSupply+amount)
}

// ── Transfers ───────────────────────────────────────────────

// SafeTransferFrom transfers \`amount\` of \`tid\` from \`from\` to \`to\`.
func SafeTransferFrom(cur realm, from, to address, tid string, amount int64) {
\tcaller := runtime.PreviousRealm().Address()

\tif !isApprovedOrOwner(caller, from) {
\t\tpanic("not approved or owner")
\t}
\tif amount <= 0 {
\t\tpanic("amount must be > 0")
\t}
\tif from == to {
\t\tpanic("cannot transfer to self")
\t}

\tfromKey := tid + ":" + from.String()
\ttoKey := tid + ":" + to.String()

\tfromBal := getBalance(fromKey)
\tif fromBal < amount {
\t\tpanic("insufficient balance")
\t}

\tbalances.Set(fromKey, fromBal-amount)
\tbalances.Set(toKey, getBalance(toKey)+amount)
}

// ── Approval ────────────────────────────────────────────────

// SetApprovalForAll approves \`operator\` to manage all of caller's tokens.
func SetApprovalForAll(cur realm, operator address, approved bool) {
\tcaller := runtime.PreviousRealm().Address()
\tif caller == operator {
\t\treturn
\t}
\tkey := caller.String() + ":" + operator.String()
\tif approved {
\t\toperatorApprovals.Set(key, true)
\t} else {
\t\toperatorApprovals.Remove(key)
\t}
}

// ── Queries ─────────────────────────────────────────────────

// BalanceOf returns the balance of \`owner\` for token \`tid\`.
func BalanceOf(owner address, tid string) int64 {
\treturn getBalance(tid + ":" + owner.String())
}

// IsApprovedForAll returns whether \`operator\` is approved for \`owner\`.
func IsApprovedForAll(owner, operator address) bool {
\treturn isApprovedOrOwner(operator, owner)
}

// TotalSupply returns the total minted supply for a token ID.
func TotalSupply(tid string) int64 {
\treturn getSupply(tid)
}

// ── Metadata ────────────────────────────────────────────────

// SetTokenURI sets a per-token URI (admin only).
func SetTokenURI(cur realm, tid string, uri string) {
\tcaller := runtime.PreviousRealm().Address()
\tif caller != address(AdminAddress) {
\t\tpanic("admin only")
\t}
\ttokenURIs.Set(tid, uri)
}

// TokenURI returns the URI for a token (per-token override or collection URI).
func TokenURI(tid string) string {
\tval, exists := tokenURIs.Get(tid)
\tif exists {
\t\treturn val.(string)
\t}
\treturn URI
}

// ── Render ──────────────────────────────────────────────────

func Render(path string) string {
\tif path == "" {
\t\treturn renderHome()
\t}
\tif strings.HasPrefix(path, "token/") {
\t\ttid := strings.TrimPrefix(path, "token/")
\t\treturn renderToken(tid)
\t}
\treturn "# 404\\nNot found: " + path
}

func renderHome() string {
\tvar sb strings.Builder
\tsb.WriteString(ufmt.Sprintf("# %s\\n\\n", Name))
\tsb.WriteString(Description + "\\n\\n")
\tsb.WriteString(ufmt.Sprintf("**URI:** %s\\n", URI))
\tsb.WriteString(ufmt.Sprintf("**Token IDs:** %d\\n", nextTokenId))

\tif MaxPerToken > 0 {
\t\tsb.WriteString(ufmt.Sprintf("**Max per token:** %d\\n", MaxPerToken))
\t}
\tsb.WriteString(ufmt.Sprintf("**Mint:** %s\\n", mintLabel()))

\tif nextTokenId > 0 {
\t\tsb.WriteString("\\n## Tokens\\n\\n")
\t\tsb.WriteString("| ID | Supply | URI |\\n")
\t\tsb.WriteString("|----|--------|-----|\\n")
\t\tfor i := int64(1); i <= nextTokenId && i <= 50; i++ {
\t\t\ttid := strconv.FormatInt(i, 10)
\t\t\tsupply := getSupply(tid)
\t\t\turi := TokenURI(tid)
\t\t\tsb.WriteString(ufmt.Sprintf("| %s | %d | %s |\\n", tid, supply, truncStr(uri, 40)))
\t\t}
\t}

\treturn sb.String()
}

func renderToken(tid string) string {
\tsupply := getSupply(tid)
\tif supply == 0 {
\t\treturn "# 404\\nToken not found: " + tid
\t}

\tvar sb strings.Builder
\tsb.WriteString(ufmt.Sprintf("# Token %s\\n\\n", tid))
\tsb.WriteString(ufmt.Sprintf("**Supply:** %d\\n", supply))
\tsb.WriteString(ufmt.Sprintf("**URI:** %s\\n", TokenURI(tid)))

\tif MaxPerToken > 0 {
\t\tsb.WriteString(ufmt.Sprintf("**Max:** %d\\n", MaxPerToken))
\t}

\treturn sb.String()
}

// ── Helpers ─────────────────────────────────────────────────

func getBalance(key string) int64 {
\tval, exists := balances.Get(key)
\tif !exists {
\t\treturn 0
\t}
\treturn val.(int64)
}

func getSupply(tid string) int64 {
\tval, exists := tokenSupply.Get(tid)
\tif !exists {
\t\treturn 0
\t}
\treturn val.(int64)
}

func isApprovedOrOwner(operator, owner address) bool {
\tif operator == owner {
\t\treturn true
\t}
\tkey := owner.String() + ":" + operator.String()
\tval, exists := operatorApprovals.Get(key)
\tif !exists {
\t\treturn false
\t}
\treturn val.(bool)
}

func mintLabel() string {
\tif PublicMint {
\t\tif MintPrice > 0 {
\t\t\treturn ufmt.Sprintf("public (%d ugnot/unit)", MintPrice)
\t\t}
\t\treturn "public (free)"
\t}
\treturn "admin only"
}

func truncStr(s string, maxLen int) string {
\tif len(s) > maxLen {
\t\treturn s[:maxLen-3] + "..."
\t}
\treturn s
}
`
}

/** Build deploy message for a GRC1155 realm. */
export function buildDeployGRC1155Msg(
    callerAddress: string,
    config: GRC1155CollectionConfig,
) {
    const code = generateGRC1155Code(config)
    const pkgName = config.realmPath.split("/").pop() || "my_editions"
    return {
        type: "/vm.m_addpkg",
        value: {
            creator: callerAddress,
            package: {
                name: pkgName,
                path: config.realmPath,
                files: [{ name: `${pkgName}.gno`, body: code }],
            },
            deposit: "",
        },
    }
}

function escapeGnoString(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")
}
