/**
 * NFT Collection Realm Template — generates Gno code for GRC721 NFT collections.
 *
 * Phase 4b: Follows channelTemplate.ts / agentTemplate.ts pattern.
 * Generates a self-contained realm with GRC721 compliance, metadata,
 * royalties, and a Render() contract for gallery display.
 *
 * @module lib/nftTemplate
 */

import { escapeGnoString } from "./templates/sanitizer"

// ── Types ────────────────────────────────────────────────────

export interface NFTCollectionConfig {
    /** Realm path (e.g., "gno.land/r/user/my_nft") */
    realmPath: string
    /** Collection name */
    name: string
    /** Collection symbol */
    symbol: string
    /** Collection description */
    description: string
    /** Creator/admin address */
    adminAddress: string
    /** Max supply (0 = unlimited) */
    maxSupply: number
    /** Royalty percentage (0-10) */
    royaltyPercent: number
    /** Whether anyone can mint or only admin */
    publicMint: boolean
    /** Mint price in ugnot (0 = free) */
    mintPrice: number
}

// ── Code Generation ──────────────────────────────────────────

export function generateNFTCollectionCode(config: NFTCollectionConfig): string {
    const pkgName = config.realmPath.split("/").pop() || "nft_collection"
    const safeName = escapeGnoString(config.name)
    const safeDesc = escapeGnoString(config.description)
    const safeSymbol = escapeGnoString(config.symbol)

    return `package ${pkgName}

// ${config.name} — GRC721 NFT Collection
// Generated by Memba NFT Marketplace (v3.0)
//
// Render() contract:
//   Home — Render(""):
//     # CollectionName
//     description
//     **Symbol:** SYM · **Supply:** N/MAX · **Creator:** g1addr
//     ## Gallery
//     - [TokenName](:token/id) — owner: g1addr
//
//   Token — Render("token/id"):
//     # TokenName
//     **Owner:** g1addr
//     **Token URI:** ipfs://...
//     **Token ID:** id

import (
	"strconv"
	"strings"

	"gno.land/p/demo/avl"
	"gno.land/p/demo/ufmt"

	"chain/banker"
	"chain/runtime"
)

// ── Constants ────────────────────────────────────────────────

const (
	CollectionName   = "${safeName}"
	CollectionSymbol = "${safeSymbol}"
	CollectionDesc   = "${safeDesc}"
	AdminAddress     = "${config.adminAddress}"
	MaxSupply        = ${config.maxSupply}
	RoyaltyPercent   = ${config.royaltyPercent}
	PublicMint       = ${config.publicMint}
	MintPrice        = int64(${config.mintPrice})
)

// ── State ────────────────────────────────────────────────────

var (
	owners         *avl.Tree // tokenId -> address
	balances       *avl.Tree // address -> int64
	tokenURIs      *avl.Tree // tokenId -> string
	tokenNames     *avl.Tree // tokenId -> string
	approvals      *avl.Tree // tokenId -> address
	opApprovals    *avl.Tree // "owner:operator" -> bool
	mintCount      int64
	tokenOrder     []string  // ordered token IDs for gallery
)

func init() {
	owners = avl.NewTree()
	balances = avl.NewTree()
	tokenURIs = avl.NewTree()
	tokenNames = avl.NewTree()
	approvals = avl.NewTree()
	opApprovals = avl.NewTree()
}

// ── GRC721 Core ──────────────────────────────────────────────

func BalanceOf(owner address) int64 {
	if val, ok := balances.Get(string(owner)); ok {
		return val.(int64)
	}
	return 0
}

func OwnerOf(tokenId string) address {
	val, ok := owners.Get(tokenId)
	if !ok {
		panic("token not found: " + tokenId)
	}
	return val.(address)
}

func TokenURI(tokenId string) string {
	val, ok := tokenURIs.Get(tokenId)
	if !ok {
		return ""
	}
	return val.(string)
}

func TotalSupply() int64 {
	return mintCount
}

func Name() string { return CollectionName }
func Symbol() string { return CollectionSymbol }

// ── Transfer ─────────────────────────────────────────────────

func TransferFrom(cur realm, from, to address, tokenId string) {
	caller := runtime.PreviousRealm().Address()
	owner := OwnerOf(tokenId)

	if owner != from {
		panic("transfer from incorrect owner")
	}
	if !isApprovedOrOwner(caller, tokenId) {
		panic("caller is not owner or approved")
	}
	if from == to {
		panic("cannot transfer to self")
	}

	// Clear approval
	approvals.Remove(tokenId)

	// Update balances
	decBalance(from)
	incBalance(to)

	// Update owner
	owners.Set(tokenId, to)
}

// ── Approval ─────────────────────────────────────────────────

func Approve(cur realm, to address, tokenId string) {
	caller := runtime.PreviousRealm().Address()
	owner := OwnerOf(tokenId)

	if caller != owner && !IsApprovedForAll(owner, caller) {
		panic("caller is not owner or approved for all")
	}
	if to == owner {
		panic("approval to current owner")
	}

	approvals.Set(tokenId, to)
}

func SetApprovalForAll(cur realm, operator address, approved bool) {
	caller := runtime.PreviousRealm().Address()
	key := string(caller) + ":" + string(operator)
	if approved {
		opApprovals.Set(key, true)
	} else {
		opApprovals.Remove(key)
	}
}

func GetApproved(tokenId string) address {
	val, ok := approvals.Get(tokenId)
	if !ok {
		return ""
	}
	return val.(address)
}

func IsApprovedForAll(owner, operator address) bool {
	key := string(owner) + ":" + string(operator)
	val, ok := opApprovals.Get(key)
	if !ok {
		return false
	}
	return val.(bool)
}

// ── Mint ─────────────────────────────────────────────────────

func Mint(cur realm, to address, tokenId, name, uri string) {
	caller := runtime.PreviousRealm().Address()

	if !PublicMint && string(caller) != AdminAddress {
		panic("only admin can mint")
	}
	if MaxSupply > 0 && mintCount >= int64(MaxSupply) {
		panic(ufmt.Sprintf("max supply reached: %d", MaxSupply))
	}
	if _, exists := owners.Get(tokenId); exists {
		panic("token already exists: " + tokenId)
	}

	// Check mint price
	if MintPrice > 0 {
		sent := banker.OriginSend()
		if sent.AmountOf("ugnot") < MintPrice {
			panic(ufmt.Sprintf("insufficient payment: need %d ugnot", MintPrice))
		}
	}

	owners.Set(tokenId, to)
	tokenURIs.Set(tokenId, uri)
	tokenNames.Set(tokenId, name)
	incBalance(to)
	mintCount++
	tokenOrder = append(tokenOrder, tokenId)
}

// ── Burn ─────────────────────────────────────────────────────

func Burn(cur realm, tokenId string) {
	caller := runtime.PreviousRealm().Address()
	owner := OwnerOf(tokenId)

	if caller != owner && string(caller) != AdminAddress {
		panic("only owner or admin can burn")
	}

	approvals.Remove(tokenId)
	decBalance(owner)
	owners.Remove(tokenId)
	tokenURIs.Remove(tokenId)
	tokenNames.Remove(tokenId)
	mintCount--
}

// ── Royalty (ERC2981) ────────────────────────────────────────

func RoyaltyInfo(tokenId string, salePrice int64) (address, int64) {
	if RoyaltyPercent == 0 {
		return "", 0
	}
	royalty := (salePrice * int64(RoyaltyPercent)) / 100
	return address(AdminAddress), royalty
}

// ── Render ───────────────────────────────────────────────────

func Render(path string) string {
	if path == "" {
		return renderHome()
	}
	if strings.HasPrefix(path, "token/") {
		tokenId := strings.TrimPrefix(path, "token/")
		return renderToken(tokenId)
	}
	return "# 404\\nNot found: " + path
}

func renderHome() string {
	var sb strings.Builder
	sb.WriteString("# " + CollectionName + "\\n\\n")
	sb.WriteString(CollectionDesc + "\\n\\n")

	maxStr := "unlimited"
	if MaxSupply > 0 {
		maxStr = strconv.FormatInt(int64(MaxSupply), 10)
	}
	sb.WriteString(ufmt.Sprintf("**Symbol:** %s · **Supply:** %d/%s · **Creator:** %s\\n\\n",
		CollectionSymbol, mintCount, maxStr, AdminAddress))

	if RoyaltyPercent > 0 {
		sb.WriteString(ufmt.Sprintf("**Royalty:** %d%%\\n\\n", RoyaltyPercent))
	}

	if len(tokenOrder) == 0 {
		sb.WriteString("*No tokens minted yet.*\\n")
		return sb.String()
	}

	sb.WriteString("## Gallery\\n\\n")
	for _, tid := range tokenOrder {
		ownerVal, exists := owners.Get(tid)
		if !exists {
			continue
		}
		owner := ownerVal.(address)
		nameVal, _ := tokenNames.Get(tid)
		name := tid
		if nameVal != nil {
			name = nameVal.(string)
		}
		sb.WriteString(ufmt.Sprintf("- [%s](:token/%s) — owner: %s\\n", name, tid, truncAddr(owner)))
	}

	return sb.String()
}

func renderToken(tokenId string) string {
	ownerVal, exists := owners.Get(tokenId)
	if !exists {
		return "# 404\\nToken not found: " + tokenId
	}
	owner := ownerVal.(address)

	var sb strings.Builder
	nameVal, _ := tokenNames.Get(tokenId)
	name := tokenId
	if nameVal != nil {
		name = nameVal.(string)
	}
	sb.WriteString("# " + name + "\\n\\n")
	sb.WriteString("**Owner:** " + string(owner) + "\\n")
	sb.WriteString("**Token ID:** " + tokenId + "\\n")

	uriVal, _ := tokenURIs.Get(tokenId)
	if uriVal != nil {
		sb.WriteString("**Token URI:** " + uriVal.(string) + "\\n")
	}

	if RoyaltyPercent > 0 {
		sb.WriteString(ufmt.Sprintf("**Royalty:** %d%% to %s\\n", RoyaltyPercent, AdminAddress))
	}

	return sb.String()
}

// ── Helpers ──────────────────────────────────────────────────

func isApprovedOrOwner(caller address, tokenId string) bool {
	owner := OwnerOf(tokenId)
	if caller == owner {
		return true
	}
	if GetApproved(tokenId) == caller {
		return true
	}
	return IsApprovedForAll(owner, caller)
}

func incBalance(addr address) {
	key := string(addr)
	if val, ok := balances.Get(key); ok {
		balances.Set(key, val.(int64)+1)
	} else {
		balances.Set(key, int64(1))
	}
}

func decBalance(addr address) {
	key := string(addr)
	if val, ok := balances.Get(key); ok {
		n := val.(int64) - 1
		if n <= 0 {
			balances.Remove(key)
		} else {
			balances.Set(key, n)
		}
	}
}

func truncAddr(addr address) string {
	s := string(addr)
	if len(s) > 13 {
		return s[:10] + "..."
	}
	return s
}
`
}

// ── Deploy Message Builder ───────────────────────────────────

export function buildDeployNFTCollectionMsg(
    callerAddress: string,
    realmPath: string,
    code: string,
) {
    const pkgName = realmPath.split("/").pop() || "nft_collection"
    return {
        type: "/vm.m_addpkg",
        value: {
            creator: callerAddress,
            package: {
                name: pkgName,
                path: realmPath,
                files: [{ name: `${pkgName}.gno`, body: code }],
            },
            deposit: "",
        },
    }
}
