import { expect, test, type Page } from '@playwright/test'
import { OS_ON } from '../../playwright.os.config'
import { abortOnchainReads } from '../helpers/onchain'

async function guest(page: Page) {
    await abortOnchainReads(page)
    await page.addInitScript(() => localStorage.setItem('memba_os_skip_intro', '1'))
}

test.describe('native OS Settings', () => {
    test.beforeEach(async ({ page }) => { await guest(page) })

    test('direct route opens the native seven-section window', async ({ page }) => {
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        const nav = win.getByRole('navigation', { name: 'Settings' })
        for (const name of ['Desktop', 'Notifications', 'Safety', 'Network', 'Transactions', 'Account', 'About']) {
            await expect(nav.getByRole('button', { name })).toBeVisible()
        }
        await expect(nav.getByRole('button', { name: 'Desktop' })).toHaveAttribute('aria-current', 'true')
        await expect(win.locator('.os-classic')).toHaveCount(0)
        await expect(win.getByRole('button', { name: 'Directory' })).toHaveCount(0)
    })

    test('appearance follows the OS preference immediately and persists', async ({ page }) => {
        await page.emulateMedia({ colorScheme: 'light' })
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        const os = page.getByTestId('memba-os')
        await win.getByRole('button', { name: 'Dark', exact: true }).click()
        await expect(os).toHaveAttribute('data-os-theme', 'dark')
        await expect.poll(() => page.evaluate(() => localStorage.getItem('memba_os_theme'))).toBe('dark')
        await expect.poll(() => page.evaluate(() => localStorage.getItem('memba_theme'))).toBeNull()
        await win.getByRole('button', { name: 'System', exact: true }).click()
        await expect(os).toHaveAttribute('data-os-theme', 'light')
        await page.emulateMedia({ colorScheme: 'dark' })
        await expect(os).toHaveAttribute('data-os-theme', 'dark')
        await page.reload()
        await expect(os).toHaveAttribute('data-os-theme', 'dark')
    })

    test('Live is a network hover/focus preview and the desktop widget is opt-in', async ({ page }) => {
        await page.setViewportSize({ width: 1280, height: 800 })
        await page.goto(`${OS_ON}/os/settings`)
        const network = page.getByRole('button', { name: 'Network: gnoland-1' })
        const widget = page.getByRole('main', { name: 'Desktop' }).locator('.os-live-ticker')
        const preview = page.getByRole('group', { name: 'Live activity preview' })
        await expect(widget).toHaveCount(0)
        await network.hover()
        await expect(preview).toBeVisible()
        await network.click()
        await expect(page.getByRole('menu', { name: 'Network' })).toBeVisible()
        await page.keyboard.press('Escape')
        await network.focus()
        await expect(preview).toBeVisible()
        const setting = page.getByRole('checkbox', { name: 'Add the Widget' })
        await setting.check()
        await expect(widget).toBeVisible()
        await page.reload()
        await expect(widget).toBeVisible()
        await page.getByRole('checkbox', { name: 'Add the Widget' }).uncheck()
        await expect(widget).toHaveCount(0)
    })

    test('wallpaper and desktop icon size apply without reload', async ({ page }) => {
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        const os = page.getByTestId('memba-os')
        const originalBackground = await os.evaluate((el) => getComputedStyle(el).backgroundImage)
        const originalTileSize = await os.locator('.os-thing .os-tile').first().evaluate((el) => getComputedStyle(el).getPropertyValue('--os-ts').trim())
        await win.getByRole('button', { name: 'Lagoon wallpaper' }).click()
        await expect(os).toHaveAttribute('data-os-wallpaper', 'lagoon')
        expect(await os.evaluate((el) => getComputedStyle(el).backgroundImage)).not.toBe(originalBackground)
        await win.getByRole('button', { name: 'Large icons' }).click()
        await expect(os).toHaveAttribute('data-os-icon-size', 'large')
        expect(await os.locator('.os-thing .os-tile').first().evaluate((el) => getComputedStyle(el).getPropertyValue('--os-ts').trim())).not.toBe(originalTileSize)
        await page.reload()
        await expect(os).toHaveAttribute('data-os-wallpaper', 'lagoon')
        await expect(os).toHaveAttribute('data-os-icon-size', 'large')
    })

    test('gas defaults validate input and use the existing preference key', async ({ page }) => {
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        await win.getByRole('navigation', { name: 'Settings' }).getByRole('button', { name: 'Transactions' }).click()
        await win.getByRole('spinbutton', { name: 'Gas wanted' }).fill('0')
        await win.getByRole('button', { name: 'Save gas defaults' }).click()
        await expect(win.getByRole('spinbutton', { name: 'Gas wanted' })).toHaveAttribute('aria-invalid', 'true')
        await expect(win.getByRole('spinbutton', { name: 'Gas wanted' })).toBeFocused()
        await expect(win.getByText('Enter a whole number from 1 to 100,000,000.')).toBeVisible()
        await win.getByRole('spinbutton', { name: 'Gas wanted' }).fill('100000001')
        await win.getByRole('button', { name: 'Save gas defaults' }).click()
        await expect(win.getByText('Enter a whole number from 1 to 100,000,000.')).toBeVisible()
        await win.getByRole('spinbutton', { name: 'Gas wanted' }).fill('100000000')
        await win.getByRole('spinbutton', { name: 'Gas fee (ugnot)' }).fill('10000001')
        await win.getByRole('button', { name: 'Save gas defaults' }).click()
        await expect(win.getByText(/1 to 10,000,000 ugnot/)).toBeVisible()
        await win.getByRole('spinbutton', { name: 'Gas wanted' }).fill('12000000')
        await win.getByRole('spinbutton', { name: 'Gas fee (ugnot)' }).fill('1500000')
        await win.getByRole('button', { name: 'Save gas defaults' }).click()
        await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('memba_settings') || '{}'))).toEqual({ gasWanted: 12000000, gasFee: 1500000 })
    })

    test('reset sheet cancels and preserves drafts and send locks on confirm', async ({ page }) => {
        await page.addInitScript(() => {
            localStorage.setItem('memba_os_terminal_draft:gnoland-1:guest', 'draft')
            localStorage.setItem('memba_os_send_lock:gnoland-1:g1test', 'lock')
        })
        await page.goto(`${OS_ON}/os/settings`)
        await expect.poll(() => page.evaluate(() => Object.keys(localStorage).find((key) => key.startsWith('memba_os_windows:')) ?? null)).not.toBeNull()
        const windowsKey = await page.evaluate(() => Object.keys(localStorage).find((key) => key.startsWith('memba_os_windows:'))!)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        await win.getByRole('navigation', { name: 'Settings' }).getByRole('button', { name: 'About' }).click()
        await win.getByRole('button', { name: 'Open About Memba OS' }).click()
        await expect(page.getByRole('region', { name: 'About Memba OS' })).toBeVisible()
        await page.getByRole('navigation', { name: 'Dock' }).getByRole('button', { name: 'Settings' }).click()
        const savedWindows = await page.evaluate((key) => localStorage.getItem(key), windowsKey)
        await win.getByRole('navigation', { name: 'Settings' }).getByRole('button', { name: 'Safety' }).click()
        await win.getByRole('button', { name: 'Reset local app data' }).click()
        const sheet = page.getByRole('dialog', { name: 'Reset local app data' })
        await expect(sheet).toBeVisible()
        await sheet.getByRole('button', { name: 'Cancel' }).click()
        await expect.poll(() => page.evaluate((key) => localStorage.getItem(key), windowsKey)).toBe(savedWindows)
        await win.getByRole('button', { name: 'Reset local app data' }).click()
        await sheet.getByRole('button', { name: 'Confirm reset' }).click()
        await expect(page.getByRole('region', { name: 'About Memba OS' })).toHaveCount(0)
        await expect.poll(() => page.evaluate((key) => localStorage.getItem(key), windowsKey)).toBeNull()
        await expect.poll(() => page.evaluate(() => localStorage.getItem('memba_os_terminal_draft:gnoland-1:guest'))).toBe('draft')
        await expect.poll(() => page.evaluate(() => localStorage.getItem('memba_os_send_lock:gnoland-1:g1test'))).toBe('lock')
        await expect(win).toBeVisible()
        await win.getByRole('button', { name: 'Close Settings' }).click()
        await page.reload()
        await expect(page.getByRole('region', { name: 'Settings', exact: true })).toHaveCount(0)
        await expect(page.getByRole('region', { name: 'About Memba OS', exact: true })).toHaveCount(0)
    })

    test('reset clears stale windows and pins in another open OS tab', async ({ page, context }) => {
        await page.goto(`${OS_ON}/os/settings`)
        await page.evaluate(() => localStorage.setItem('memba_os_desk:mainnet:guest', JSON.stringify([{ ty: 'app', ref: 'feed', c: 0, r: 0 }])))
        const other = await context.newPage()
        await guest(other)
        await other.goto(`${OS_ON}/os/settings`)
        const otherSettings = other.getByRole('region', { name: 'Settings', exact: true })
        await expect(other.locator('[data-item="app:feed"]')).toBeVisible()
        await otherSettings.getByRole('button', { name: 'About', exact: true }).click()
        await otherSettings.getByRole('button', { name: 'Open About Memba OS' }).click()
        await expect(other.getByRole('region', { name: 'About Memba OS', exact: true })).toBeVisible()

        const settings = page.getByRole('region', { name: 'Settings', exact: true })
        await settings.getByRole('button', { name: 'Safety', exact: true }).click()
        await settings.getByRole('button', { name: 'Reset local app data' }).click()
        await page.getByRole('dialog', { name: 'Reset local app data' }).getByRole('button', { name: 'Confirm reset' }).click()

        await expect(other.getByRole('region', { name: 'About Memba OS', exact: true })).toHaveCount(0)
        await expect(otherSettings).toBeVisible()
        await expect(other.locator('[data-item="app:feed"]')).toHaveCount(0)
        await expect(other.locator('[data-item="dao:govdao"]')).toBeVisible()
        await expect.poll(() => other.evaluate(() => ({
            desk: localStorage.getItem('memba_os_desk:mainnet:guest'),
            windows: Object.keys(localStorage).filter((key) => key.startsWith('memba_os_windows:')),
        }))).toEqual({ desk: null, windows: [] })
        await other.close()
    })

    test('account and About remain available to guests', async ({ page }) => {
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        const nav = win.getByRole('navigation', { name: 'Settings' })
        await nav.getByRole('button', { name: 'Account' }).click()
        await expect(win.getByRole('button', { name: 'Connect wallet' })).toBeVisible()
        await nav.getByRole('button', { name: 'About' }).click()
        await win.getByRole('button', { name: 'Open About Memba OS' }).click()
        await expect(page.getByRole('region', { name: 'About Memba OS' })).toBeVisible()
    })

    test('phone Settings remains navigable without horizontal overflow', async ({ page }) => {
        await page.setViewportSize({ width: 390, height: 844 })
        await page.goto(`${OS_ON}/os/settings`)
        const sheet = page.locator('.os-ph-sheet')
        await expect(sheet.getByRole('navigation', { name: 'Settings' })).toBeVisible()
        await sheet.getByRole('button', { name: 'Safety' }).click()
        await expect(sheet.getByRole('button', { name: 'Reset local app data' })).toBeVisible()
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 4)).toBe(true)
    })

    test('Settings content fits a narrow desktop window', async ({ page }) => {
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        await win.evaluate((el) => { (el as HTMLElement).style.width = '360px' })
        await expect(win.getByRole('button', { name: 'Lagoon wallpaper' })).toBeVisible()
        expect(await win.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
    })

    test('reset dialog contains focus and its actions stay reachable on a short phone viewport', async ({ page }) => {
        await page.setViewportSize({ width: 320, height: 256 })
        await page.goto(`${OS_ON}/os/settings`)
        const sheet = page.locator('.os-ph-sheet')
        await sheet.getByRole('button', { name: 'Safety' }).click()
        await sheet.getByRole('button', { name: 'Reset local app data' }).click()
        const dialog = page.getByRole('dialog', { name: 'Reset local app data' })
        await expect(dialog.getByRole('button', { name: 'Cancel' })).toBeVisible()
        await expect(dialog.getByRole('button', { name: 'Confirm reset' })).toBeVisible()
        await page.keyboard.press('Control+k')
        await expect(dialog.getByRole('button', { name: 'Cancel' })).toBeFocused()
        await page.keyboard.press('Alt+w')
        await expect(sheet).toBeVisible()
        await page.keyboard.press('Escape')
        await expect(dialog).toHaveCount(0)
        await expect(sheet.getByRole('button', { name: 'Reset local app data' })).toBeFocused()
    })

    test('an already-open Settings window follows a new section deep link', async ({ page }) => {
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        await page.evaluate(() => { history.pushState(null, '', '/os/settings/transactions'); dispatchEvent(new PopStateEvent('popstate')) })
        await expect(win.getByRole('navigation', { name: 'Settings' }).getByRole('button', { name: 'Transactions' })).toHaveAttribute('aria-current', 'true')
        await expect(win.getByRole('spinbutton', { name: 'Gas wanted' })).toBeVisible()
        await page.evaluate(() => { history.pushState(null, '', '/os/settings/unknown'); dispatchEvent(new PopStateEvent('popstate')) })
        await expect(win.getByText('Nothing lives here')).toBeVisible()
    })

    test('stale gas edits cannot overwrite another tab', async ({ page, context }) => {
        await page.goto(`${OS_ON}/os/settings`)
        const win = page.getByRole('region', { name: 'Settings', exact: true })
        await win.getByRole('button', { name: 'Transactions' }).click()
        await win.getByRole('spinbutton', { name: 'Gas wanted' }).fill('12000000')
        const other = await context.newPage()
        await other.goto(`${OS_ON}/os/settings`)
        await other.evaluate(() => localStorage.setItem('memba_settings', JSON.stringify({ gasWanted: 9000000, gasFee: 1500000 })))
        await win.getByRole('button', { name: 'Save gas defaults' }).click()
        await expect(win.getByRole('alert')).toContainText('changed elsewhere')
        await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('memba_settings') ?? '{}'))).toEqual({ gasWanted: 9000000, gasFee: 1500000 })
        await win.getByRole('button', { name: 'Load latest gas defaults' }).click()
        await expect(win.getByRole('spinbutton', { name: 'Gas wanted' })).toHaveValue('9000000')
        await other.close()
    })
})
